### ISSUE TITLE
keystore登录转为服务器托管时，输入重复邮箱，提示不友好

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#10]
【bug标题】keystore登录转为服务器托管时，输入重复邮箱，提示不友好
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.原本是keystore是自己保存的，登录时选择keystore保存到服务器，
2.填写了一个邮箱（该邮箱已经被注册过pressone页面）
3.提示：Duplicated keystore. 这个提示很不友好，普通用户不懂，明明就是邮箱重复了嘛，应该提示邮箱重复了
4.稍微友好一点的方式是，邮箱地址输入后，有一个自动检测邮箱地址是否重复的功能，并给与用户准确的反馈

【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/38823541-3fece5c0-41d9-11e8-83ac-3b064bab2f85.png)

![image](https://user-images.githubusercontent.com/31027645/38823545-43f81784-41d9-11e8-8602-8e785451ae92.png)

**Comment by raimonfuns** [comment]
已修复
