### ISSUE TITLE
机构类帐号，当前外网正式版，是有“创建新项目”功能的；但在beta中，不存在这个功能入口

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#100]
bug标题：机构类帐号，当前外网正式版，是有“创建新项目”功能的；但在beta中，不存在这个功能入口

测试版本：https://beta.press.one/

复现步骤：在beta中，登入机构类测试账号，没有发现“创建新项目”的功能入口

预期效果：机构类帐号应该有“创建新项目”的功能入口

**Comment by Xiqiao** [comment]
已修正
