### ISSUE TITLE
PressOne文章写作界面，新输入文字覆盖原文字

### ISSUE THREAD

**Issue by youyou-579** [Press-One/issues#102]
PressOne写文章的时候，如果在文章中间，进行文字修改，会自动覆盖后面的文字。类似于word文档中，点击了insert后，新输入的文字，会取代后面的原文字一样。目前的解决办法是，在修改之前，按enter换行，能避免后面的文字覆盖。

希望能自由选择是否覆盖，或者取消掉覆盖的设置，因为一不小心就覆盖了，需要撤销修改或者重新输入已覆盖的文字，体验很不好。

**Comment by raimonfuns** [comment]
@youyou-579 你好，我不能重现你说的现象，能否提供一张 gif 、以及使用的电脑系统和浏览器？

**Comment by raimonfuns** [comment]
由于 @youyou-579 还没有回复，我先关掉这个 issue。
如果后续能重现这个问题，再重新打开。
