### ISSUE TITLE
不应该在他人主页下显示自己的 mixin id

### ISSUE THREAD

**Issue by qige-one** [Press-One/issues#103]
【测试版本】press.one 正式版
【测试环境】Chrome / macOS
【复现频次】必现
【复现步骤】
1. 点开收到的新手任务（绑定送 3 PRS）的推送消息
2. 在新弹窗中，有 `来自 PRS 新人促进基金` 字样，此时点击“PRS 新人促进基金” 的链接
3. 此时进入到 “PRS 新人促进基金” 的主页；左侧栏有：我的 Mixin ID 及 我的 BigONE 账号ID 等信息 ——【此处不应该显示这些信息】

**Comment by raimonfuns** [comment]
已修复
