### ISSUE TITLE
外部认证信息失效时，将其在 P1 认证信息里去掉比较好

### ISSUE THREAD

**Issue by qige-one** [Press-One/issues#104]
比如：
对于账号 https://press.one/main/p/e0b2908b00ecc554e460863ee43481b8d47e8641 ，其 twitter 认证信息：https://twitter.com/SonePres/status/996802716847362049 只显示：
> Account suspended
> This account has been suspended. Learn more about why Twitter suspends accounts, or return to your timeline.
此时将在 p1 主页里去掉其 twitter 认证信息比较好

**Comment by raimonfuns** [comment]
@qige-one 如果链接失效了，从技术上来考虑，我们并不打算把 icon 隐藏掉，这里的成本太高。对于用户来说，如果希望增强身份的可信读，那么他需要使用有效的链接。
