### ISSUE TITLE
最新遇到的Bug：PressOne写文章，可不可以重新编辑？

### ISSUE THREAD

**Issue by JiuOneOne** [Press-One/issues#108]
1.新浪微博与steemit身份认证，完成添加完微博或文章的页面网址后，确认 3 把该条“包含您数字签名信息的页面网址”保存到区块链上，出现 “抱歉，你返回的页面中没有包含数字签名，或数字签名链接显示不完整，请修正后重试”，改了好几次都是这样的结果。之后再操作知乎却没有出现该问题。

2.签发的文字有没有可能修改错别字呢？就是那种划掉改正确的，就像老师批改学生作业加批注的方式，这样既保留了痕迹，又不至于眼睁睁看着错的，却改不了好太多。可不可以在微信订阅号文章改错字功能上优化一下这个。

**Comment by JiuOneOne** [comment]
https://press.one/p/address/v?s=d468363f39b61888900c94d55bf89f92bf4f65dce56d36fe1fe8a5d01914048f9e5b3802fae93ab818a8338f2abf8dbc1b16a142f83f4950a357acaf902fc2cf0&h=f18685bfc8d39c66fa5c3ed1caac87b95a077156227f22afab013e8b85cbe05e&a=255341013bd8a7549c379e4ec910477f0e85a538&f=P1&v=2

**Comment by raimonfuns** [comment]
@JiuOneOne 
1. 微博由于有缓存，有可能会出现这种延时的问题。一般等几分钟再试就能成功的。
2. 发布文章其实就是把内容写到链上，一旦写上之后，就不能再篡改了，所以是无法修改的。会考虑增加文章的删除功能，如果有错别字，可以删掉文章，然后重新创建一篇新文章。
