### ISSUE TITLE
[Android-Vital] 自带的webview页面 绑定minxin 奔溃

### ISSUE THREAD

**Issue by yulinliujian** [Press-One/issues#109]
自带的webview页面 绑定minxin 奔溃
![1](https://user-images.githubusercontent.com/29038837/42254013-30256c30-7f77-11e8-8f2c-4961e59c5670.jpg)
![2](https://user-images.githubusercontent.com/29038837/42254017-36010952-7f77-11e8-8182-f3d8a6ef4850.jpg)
![3](https://user-images.githubusercontent.com/29038837/42254028-3b6c99a6-7f77-11e8-90cb-0474532eab8b.jpg)

锤子手机，安卓7.1.1M,  Mixin ID：20771

**Comment by raimonfuns** [comment]
@yulinliujian 多谢反馈问题。这看起来像是网络问题，我刚才用试了一下，是正常的。你再试几次，看能不能重现，也可以在正式环境 https://press.one 试试。

**Comment by ryanhoo** [comment]
@yulinliujian 收到，会尽快修复。

**Comment by ryanhoo** [comment]
已修复，等新版本发布。@yulinliujian 

**Mixin ID**: 20771
**奖励**：10 PRS

```
commit ad925249d8acead39bc7a8cb47b986b62970e9a7
Author: Ryan Hoo <ryan.hoo.j@gmail.com>
Date:   Wed Jul 4 17:33:10 2018 +0800

    fix(webview): loading issues

    - failed to load page and swipe refresh conflicts when body.height=100%
    - resuable WebViewClient code
    - support all none http/https links
```
