### ISSUE TITLE
注册填写邮箱时，仅填带@的任意字符串也能注册

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#11]
【bug标题】注册填写邮箱时，仅填带@的任意字符串也能注册
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.注册填写邮箱时，输入aaa@bbb这类字符串，也能正常注册
2.可aaa@bbb根本不是一个有效邮箱，这个功能并没有检查用户的邮箱地址是否准确，既然是任意字符串，为啥还要要求邮箱地址？
3.
【bug截图】
【备注】

**Comment by raimonfuns** [comment]
已修复
