### ISSUE TITLE
[网站]机构帐号修改单个项目公告时导致主页公告被修改

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#110]
PC端，谷歌浏览器
拓荒者基金主页：https://press.one/main/p/e0b2908b00ecc554e460863ee43481b8d47e8641
步骤：
1、拓荒者基金主页，公告，记为：【位置X】，公告内容，标记【内容A】
2、此时点击拓荒者之旅4期项目名字，进入项目页面，注意查看，此时的公告栏显示的是单个项目的公告记为：【位置Y】，公告内容，标记【内容B】。
3、点击公告栏旁边的编辑按钮，并修改公告。进入编辑栏，修改公告内容，记为【内容C】。
4、当时【内容B】立即正常变成了【内容C】
5、刷新本页面，【位置Y】处的【内容C】不见了，依然是【内容B】；而基金主页的【内容A】变成了【内容C】

原本对应关系：
基金主页：位置X - 内容A
单个项目：位置Y - 内容B

尝试在位置Y，修改内容B → 内容C

修改后对应关系：（当前表现）
位置X - 内容C
位置Y - 内容B

预期实现：
位置X - 内容A
位置Y - 内容C

------

症结在于：单个项目公告页的右上角编辑入口，其实就是主页编辑入口？

**Comment by raimonfuns** [comment]
@liujuanjuan1984 好滴，会尽快修复

**Comment by wuhaoa** [comment]
fixed.
