### ISSUE TITLE
PRESS.one个人页面-英文版 设置 交易记录单词拼写错误

### ISSUE THREAD

**Issue by jadylotus** [Press-One/issues#111]
PRESS.one个人页面-英文版
设置
交易记录Tranaction 写成 Sranaction
![default](https://user-images.githubusercontent.com/31565588/42356334-7fca5d34-8104-11e8-9ddf-a6f32337ce5f.png)

**Comment by raimonfuns** [comment]
@jadylotus 
已修复。

奖励：2 PRS
