### ISSUE TITLE
iOS-Vitual 程序不响应

### ISSUE THREAD

**Issue by Liuruyong** [Press-One/issues#112]
# 环境
iPhone SE, iOS 11.3.2 , PressOne Beta版(1.0.0.36)

# 复现步骤
1. 打开press one，按home键
2. 再次打开press one，会有近5s的不响应时间

频繁的打开应用，按home键，不响应时间会累加。

# MixinID
213318

**Comment by ElvisZP** [comment]
@Liuruyong 
你好，我这边暂时不能重现。
你那能否提供操作视频呢？看看在最新的版本里是否还会复现。

**Comment by ElvisZP** [comment]
已修复，等新版本发布。
@Liuruyong 

Mixin ID: 213318
奖励：10 PRS
