### ISSUE TITLE
iOS-Urgent beta版我的身份证明，跳转到正式环境网址

### ISSUE THREAD

**Issue by Liuruyong** [Press-One/issues#113]
# 环境
iPhone SE, iOS 11.3.2 , PressOne Beta版(1.0.0.36)

# 复现步骤
1. 点击我的身份证明
2. 选择打开网页

会跳转到正式环境页面。习惯性输入测试环境账号密码，提示密码错误。

# MixinID
213318

**Comment by ElvisZP** [comment]
已修复.

Mixin ID: 213318
奖励：5 PRS
