### ISSUE TITLE
ios扫码查看或者订阅，对方帐号头像不显示

### ISSUE THREAD

**Issue by pphaolu** [Press-One/issues#114]
正式版环境
ios扫码查看或者订阅，对方帐号头像不显示
![2e7530ad1fedaa3c824baadac4d2e2c6](https://user-images.githubusercontent.com/35622701/42436649-3eb213ec-838d-11e8-8f89-98acc9c95aa2.png)
![0dcbc1cad7f9e5cbbf94f9f471989c34](https://user-images.githubusercontent.com/35622701/42436651-4188e7ee-838d-11e8-9798-8d8bde6ad7d4.png)

实际上是有头像的
![image](https://user-images.githubusercontent.com/35622701/42436671-4f6c8348-838d-11e8-9f9d-8f82a837ab5d.png)

**Comment by ElvisZP** [comment]
3月份之前上传的头像托管在google上，所以需要翻墙之后才能访问。
现在上传的头像都能够直接访问。
