### ISSUE TITLE
[Android-Minor]第一次安装时桌面图标与其他APP图标重叠

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#115]
【测试版本】180704版本（未查看版本号）
【测试环境】小米8，安卓8.1.0(MIUI 9.5)
【复现频次】第一次安装时，再次安装时无复现
【复现步骤】
1.从google play安装测试版APP，安装完成后点击打开。
2.打开APP后，关闭APP。
3.返回到桌面，发现PRESS.one的桌面图标与其他APP图标重叠。
点击该图标可以正常进入PRESS.one，但被重叠的APP无法进入。
4.重启手机后，桌面图标位置恢复正常。
【Mixin ID】1069021

【截图】
![20180710094221](https://user-images.githubusercontent.com/38434418/42484449-a72eff8c-8425-11e8-93a5-62a8db6894f7.jpg)
![20180710094308](https://user-images.githubusercontent.com/38434418/42484462-b0500e4e-8425-11e8-9bbf-25cd137a1333.jpg)
![20180710094334](https://user-images.githubusercontent.com/38434418/42484482-c58c41d8-8425-11e8-95bb-bc0e64f160b9.jpg)

**Comment by ryanhoo** [comment]
这个应该是 MIUI 的 bug... App 不会单独创建桌面图标。
