### ISSUE TITLE
[Android-Minor]进入首页，两处引导动效的样式未对准

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#116]
【测试版本】2.0.0.705
【测试环境】小米8，安卓8.1.0(MIUI 9.5)
【复现频次】总是
【复现步骤】
1.新账号完成注册后跳转到首页。
2.发现右上角的三点菜单，引导动效的圆心在三点的最上一个点的位置。
3.点击三角菜单按钮，我的身份证明下引导动效亮起。
4.我的身份证明下，引导动效圆心在圆形icon的最右的边缘上。
【Mixin ID】1069021

【截图】
![20180710094936](https://user-images.githubusercontent.com/38434418/42484833-6f8cb87e-8427-11e8-9a14-ee30d16297e9.jpg)
![20180710095003](https://user-images.githubusercontent.com/38434418/42484836-73eb559c-8427-11e8-84fe-01a5faf157bb.jpg)

**Comment by chaoslaw2018** [comment]
再补充一处，我的签名这里，见图：
![20180710110019](https://user-images.githubusercontent.com/38434418/42486791-6b5ebd48-8430-11e8-8b5e-87114b4a70bc.jpg)

**Comment by ryanhoo** [comment]
非常感谢测试得这么细致，不过这个是故意的，目的是为了让用户能注意到。如果跟蓝色按钮对齐，会很难察觉到。
