### ISSUE TITLE
[Android-Minor]交易历史页面，上下两处Mixin大小写不统一

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#117]
【测试版本】2.0.0.705
【测试环境】小米8，安卓8.1.0(MIUI 9.5)
【复现频次】总是
【复现步骤】
1.未绑定Mixin时进入交易历史页面。
2.上方文字说明中写的是”Mixin“，下方按钮中写的是”MIXIN“。
【Mixin ID】1069021

【截图】
![20180710100320](https://user-images.githubusercontent.com/38434418/42485039-654721b4-8428-11e8-94e1-3a78942b72bf.jpg)

**Comment by ryanhoo** [comment]
前几天已经修复了，等新版本上线。
