### ISSUE TITLE
[Android-Urgent]绑定完Mixin后，个人首页绑定Mixin的状态没有即时更新

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#118]
【测试版本】2.0.0.705
【测试环境】小米8，安卓8.1.0(MIUI 9.5)
【复现频次】总是
【复现步骤】
1.新账号从交易历史页面点击绑定MIXIN。
2.成功绑定Mixin。
3.返回到APP的个人首页，发现我的Mixin ID仍然显示未绑定。
4.登出再重新登录后，APP个人首页能够正常显示已绑定的Mixin ID。
【Mixin ID】1069021

【截图】
![20180710103255](https://user-images.githubusercontent.com/38434418/42485980-8c6fd5ac-842c-11e8-97f0-cc98ca014d47.jpg)

**Comment by ryanhoo** [comment]
已修复，等新版本发布。 @chaoslaw2018

**Mixin ID**: 1069021
**奖励**：4 PRS

```
commit 9884905248c8e57ac788be2cd4c10ab1dba8703f
Author: Ryan Hoo <ryan.hoo.j@gmail.com>
Date:   Thu Jul 12 14:07:12 2018 +0800

    feat(profile): update profile periodically
```
