### ISSUE TITLE
[Android-Minor]APP跳转到网页版后，英文版按钮换行

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#119]
【测试版本】2.0.0.705
【测试环境】小米8，安卓8.1.0(MIUI 9.5)
【复现频次】总是
【复现步骤】
1.从APP中跳转到网页版。
2.在首页切换为英文版本。
3.跳转到微信文章的按钮文字换行了。
【Mixin ID】1069021

【截图】
![20180710103448](https://user-images.githubusercontent.com/38434418/42486116-2ac3289e-842d-11e8-9f63-46353a18237b.jpg)

**Comment by ryanhoo** [comment]
@chaoslaw2018 英文翻译有点过于啰嗦了，我们需要精简下。
