### ISSUE TITLE
[Android-Urgent]跳转到网页版后，登录时点击选择keynote没有反应

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#120]
【测试版本】2.0.0.705
【测试环境】小米8，安卓8.1.0(MIUI 9.5)
【复现频次】总是
【复现步骤】
1.登录APP，跳转到网页版。
2.登录时选择使用keynote登录。
3.点击选择keynote的框，没有任何反应。
【Mixin ID】1069021

【截图】
![20180710104137](https://user-images.githubusercontent.com/38434418/42486277-c08fed30-842d-11e8-89e9-7434efecedd4.jpg)

**Comment by ryanhoo** [comment]
已修复，等新版本发布。 @chaoslaw2018

**Mixin ID**: 1069021
**奖励**：5 PRS

```
commit 50d7b231d1fea7a7db4b11405e73dba5f0ccfe35
Author: Ryan Hoo <ryan.hoo.j@gmail.com>
Date:   Thu Jul 12 15:19:53 2018 +0800

    fix(webview): cannot upload keystore file
```
