### ISSUE TITLE
[Android-Urgent]编辑内容签名页面，无法进行复制粘贴

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#121]
【测试版本】2.0.0.705
【测试环境】小米8，安卓8.1.0(MIUI 9.5)
【复现频次】总是
【复现步骤】
1.APP登录，跳转到网页版。
2.点击创建内容签名。
3.在创建内容签名页面，无法通过长按输入框弹出复制粘贴选项。
【Mixin ID】1069021

**Comment by ryanhoo** [comment]
已修复，等新版本发布。 @chaoslaw2018

**Mixin ID**: 1069021
**奖励**：5 PRS

```
commit 0be480ae464be30fa1b88f22009b4c3ee56fb8af
Author: Ryan Hoo <ryan.hoo.j@gmail.com>
Date:   Thu Jul 12 14:58:19 2018 +0800

    fix(webview): unable to popup select/copy/past dialog
```
