### ISSUE TITLE
[Android- Urgent] APP对密码有6位字符的校验，通过网页版注册的用户如密码低于6位字符则无法使用

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#122]
【测试版本】2.0.0.705
【测试环境】小米8，安卓8.1.0(MIUI 9.5)
【复现频次】总是
【复现步骤】
1.在网页版注册，密码小于6位字符。
2.在APP登录该账号。
3.登录页面提示密码不能小于6位字符，该账号无法登录APP。
【Mixin ID】1069021

**Comment by ryanhoo** [comment]
已修复，等新版本发布。现在支持短密码登录，但是新注册密码必须大于 6 位。 @chaoslaw2018

**Mixin ID**: 1069021
**奖励**：5 PRS
