### ISSUE TITLE
[Android-Urgent]APP中网页版进行身份证明的弹层中，到底后下滑会自动刷新

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#123]
【测试版本】2.0.0.705
【测试环境】小米8，安卓8.1.0(MIUI 9.5)
【复现频次】总是
【复现步骤】
1.APP中跳转到网页版。
2.点击添加身份证明。
3.在身份证明相关弹层中滑到最底部。
4.此时进行下滑操作，无法回到页面上方，而是自动刷新了页面。
【Mixin ID】1069021

【截图】
![20180710110608](https://user-images.githubusercontent.com/38434418/42486973-66fa0be4-8431-11e8-844e-b0b51be04fcf.jpg)
![20180710110636](https://user-images.githubusercontent.com/38434418/42487002-840a7bce-8431-11e8-9aed-10168edb54d6.jpg)
![20180710110733](https://user-images.githubusercontent.com/38434418/42487012-8c1600d6-8431-11e8-8d49-c71099292d35.jpg)

**Comment by ryanhoo** [comment]
已修复，等新版本发布。 @chaoslaw2018

Mixin ID: 1069021
奖励：10 PRS

实际上跟 issue #124 引起的原因是一样的。这个 bug 虽然表现不一样，但是原因都是因为 android webview 中的内容设置为 height:100%，然后滚动事件将由 webview 接管，因此会触发下拉刷新。
