### ISSUE TITLE
[Android-Vital]在网页版中登录和APP中不一致的账号，登录后白屏

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#124]
【测试版本】2.0.0.705
【测试环境】小米8，安卓8.1.0(MIUI 9.5)
【复现频次】总是
【复现步骤】
1.在APP中登录账号A。
2.跳转到网页版。
3.登录账号B或者注册账号C。
4.登录或注册完成后，跳转页面显示为白屏。
【Mixin ID】1069021

【截图】
![20180710111411](https://user-images.githubusercontent.com/38434418/42487155-48548a1a-8432-11e8-9b7e-ac36fa9f3d6d.jpg)

**Comment by ryanhoo** [comment]
已修复，等新版本发布。 @chaoslaw2018 

Mixin ID: 1069021
奖励：10 PRS

```
commit dd3e429416b006e942664b2290c73bd5d9d1adc1
Author: Ryan Hoo <ryan.hoo.j@gmail.com>
Date:   Thu Jul 12 13:34:25 2018 +0800

    fix(webview): scrolling issues
```
