### ISSUE TITLE
注册时可以使用任意邮箱

### ISSUE THREAD

**Issue by dezng** [Press-One/issues#125]
今天准备登录时候发现忘记邮箱了，找了各个邮箱也没有看到相关邮件，最后发现邮箱用错了，名称后面漏掉了 s

**Comment by dezng** [comment]
![image](https://user-images.githubusercontent.com/7430257/42491460-68c00d3c-8447-11e8-9509-d295c0106b09.png)
刚好博客里面看到一个描述，好像也是漏掉了一个字，`动(态)计算授权价格和发放授权协议`

**Comment by raimonfuns** [comment]
@dezng 邮箱只要符合格式，都是可以注册的。我们并不验证邮箱的有效性。
博客漏掉的字，已经补上了。多谢你发现这个错误。
