### ISSUE TITLE
[网站]浏览器在A页签已登入，B页签打开PRS网页未同步登入状态

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#126]
环境：PC chrome浏览器，同一个窗口，多个页签访问：
操作步骤：
在A页签PRS登入a帐号，在B页签通过打开一个新的PRS网址访问PRS依然是未登入状态
打开一个新的PRS网址方式有：直接输入PRS的网址访问，或者点击收藏夹中PRS地址

期望表现：
在A页签PRS登入a帐号，在B页签通过打开一个新的PRS网址访问PRS是已登入状态

**Comment by raimonfuns** [comment]
@liujuanjuan1984 登录、注册功能之后会有一个大改版，流程会有比较大的改变。到时候这个问题会一起优化。
