### ISSUE TITLE
[网站]在他人主页上点击【我的页面】，签名内容依然为他人内容

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#127]
环境：windows，chrome

操作：
1、登入本人账号：https://press.one/main/p/ed73e900e209def08ff03a2e3fadbac99af087c0

2、访问他人主页：https://press.one/main/p/f696ffeb49cce1907bebb61e741a61758948d939

![image](https://user-images.githubusercontent.com/31027645/42523296-f2b311da-849f-11e8-8d99-8102b9967d58.png)

3、在该页面点击右上角操作选项【我的页面】，结果个人信息刷新；但签名内容未刷新，依然为他人主页的签名内容。

![image](https://user-images.githubusercontent.com/31027645/42523333-0714a328-84a0-11e8-9c1c-8644728ae03f.png)

**Comment by raimonfuns** [comment]
@liujuanjuan1984 
已修复。

奖励：10 PRS
