### ISSUE TITLE
[网站]在已登录的状态下点击订阅会跳转到登录页面

### ISSUE THREAD

**Issue by bitplus** [Press-One/issues#128]
PC端，谷歌浏览器，已登录PRESS.one，访问某个个人页面时点击订阅按钮会跳转到登录页面

步骤：
1. 新建浏览器标签页，打开网址https://press.one/main/p/e0b2908b00ecc554e460863ee43481b8d47e8641
2.点击订阅按钮
![image](https://user-images.githubusercontent.com/1134765/42555002-78b85c3a-8519-11e8-9548-6558ce31fe7e.png)

**Comment by bitplus** [comment]
PC端，谷歌浏览器，已登录PRESS.one，访问某个个人页面时点击订阅按钮会跳转到登录页面

步骤：
1. 新建浏览器标签页，打开网址https://press.one/main/p/e0b2908b00ecc554e460863ee43481b8d47e8641
2.点击订阅按钮
![image](https://user-images.githubusercontent.com/1134765/42554705-753f9970-8518-11e8-996f-600e990b17d4.png)

**Comment by raimonfuns** [comment]
@bitplus 
这个问题和这个 [issue](https://github.com/Press-One/issues/issues/126) 应该是同一个问题。

因为目前登录的实现方式问题，登录的状态只存在于当前 tab 页面，如果是新打开一个页面，登录状态就没有了。

登录、注册功能之后会有一个大改版，流程会有比较大的改变。到时候这个问题会一起优化。
