### ISSUE TITLE
个人简介/名字/职业等输入框没有限制字符长度，或字符长度过长

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#13]
【bug标题】个人简介/名字/职业等输入框没有限制字符长度，或字符长度过长
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.在个人页面编辑个人简介，一直输入一直输入，复制粘贴*N次
2.可以正常保存且能发布，导致个人介绍长达数屏
3.个人简介完全没有限制字符长度？
4.再次尝试复制了超长超长内容，无法保存，并提示warningsaveBasicInfo error: Bad Request
5.除了个人签名，名字，职业等2个输入框也没有做输入长度的限制，或已有限制不合理
【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/38824196-066032c4-41db-11e8-985f-5bf6e5b5e8f4.png)
****
![image](https://user-images.githubusercontent.com/31027645/38846178-ac1120be-422d-11e8-8749-9764ba73459c.png)

![image](https://user-images.githubusercontent.com/31027645/38856788-014a9944-425a-11e8-83a3-4cfdf1711096.png)

**Comment by raimonfuns** [comment]
已优化
