### ISSUE TITLE
[iOS Vital ]测试版和正式版，在我的订阅中会卡顿或无响应问题

### ISSUE THREAD

**Issue by Jiudus** [Press-One/issues#130]
步骤：
1.进入“我的订阅”
2.点击任意已订阅或未订阅的内容
3.在短暂的读取内容过程中，若立即点“订阅”或“取消订阅”，很容易出现长时间的卡顿甚至一直无响应问题。在卡顿或无响应期间，点击任何功能无效，只能强行退出程序重进。

测试版问题图：
![image](https://user-images.githubusercontent.com/41194694/42696848-ffd99fc0-86eb-11e8-96dd-324a8fb1dfe4.png)

正式版问题图：
![image](https://user-images.githubusercontent.com/41194694/42696841-f96aa72e-86eb-11e8-8a83-58b64d19a61e.png)

附加信息：
系统版本：iphone6s  ios11.4(15F79)
App 版本：Test/正式版   Version1.0.0(1.0.0.39)
Mixin ID ：27503

**Comment by ElvisZP** [comment]
已修复，等新版本发布。

Mixin ID: 27503
奖励：15 PRS

**Comment by Jiudus** [comment]
请问这个什么时候发呢？没漏掉吧？






在 2018-07-16 15:19:41，"ElvisZP" <notifications@github.com> 写道：


已修复，等新版本发布。

Mixin ID: 27503
奖励：15 PRS
