### ISSUE TITLE
[网站]blog首页阅读文章时大图片显示不完整，不会自动缩放

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#131]
**环境**：pc，chrome浏览器
**操作步骤**：
访问官方blog，查看711发布的这篇文章，发现部分大图片显示不完整；哪怕缩放浏览器到70%之类，依然无法显示完整。
预期实现：超大图片能自动根据窗口缩放到可预览全图的尺寸，点击后可以查看高清大图。
访问网址：https://blog.press.one/?from=https://press.one
相关截图：
![image](https://user-images.githubusercontent.com/31027645/42762141-11015f10-8942-11e8-9341-7a5b8efe6e88.png)

**Comment by raimonfuns** [comment]
已修复。

奖励：5 PRS.
