### ISSUE TITLE
[网站]在微信中打开pressone的任务链接，无法预览

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#132]
操作步骤：
在微信中打开pressone的任务链接，直接显示为输入账号密码登入页面

预期实现：可以预览任务，点击领取时才要求登入。

**Comment by imeoer** [comment]
因为该页面中任务的状态和用户相关，目前匿名用户打开任务链接时，会重定向到登录页，登录后重定向到任务详情页。这里的确可以改成匿名用户可访问的。

**Comment by imeoer** [comment]
已经改善，非常感谢反馈。
