### ISSUE TITLE
[网站]只能点开单个项目去查看任务列表，不能查看该账号下所有任务

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#133]
环境：pc，chrome
操作步骤：
1、想要查看基金帐号下发布的任务，只能点开单个项目去查看该项目下的任务列表
预期实现：
能查看上一级、不限项目的所有任务列表

**Comment by imeoer** [comment]
一种解决方案是在基金账户页面多加一个任务列表 tab，显示账户所有相关任务。

**Comment by imeoer** [comment]
后续更新：任务和基金账户相关，都罗列在一起易混淆，暂时不做处理。
