### ISSUE TITLE
PRS打赏流程问题

### ISSUE THREAD

**Issue by Chao2015cc** [Press-One/issues#134]
### 问题描述：
- 文章详情中进行打赏操作，跳转到mixin钱包支付完成后，返回到文章详情之后，文章中打赏金额数未增加，且press.one中的的交易历史中也没有支持记录。

### 问题等级
- 紧急且高优先级。

### 波及范围
- PC web端、Mobile Web端、iOS客户端（1.0.0.41）
- Android版本因未安装客户端尚未测试。

### 解决方案
- 修复金额未同步的问题，并且将bug产生期间丢失的赞赏数及交易记录找回。

@ElvisZP @raimonfuns @ryanhoo

**Comment by raimonfuns** [comment]
已修复。
