### ISSUE TITLE
App个人信息丢失

### ISSUE THREAD

**Issue by huoguanghua** [Press-One/issues#136]
已经在Web上绑定了bigone的ID，但是在App上看不到。
用户头像在App上也不显示了

**Comment by raimonfuns** [comment]
@huoguanghua 由于 bigone 目前暂时不提供 bigone ID，所以 web 和 app 的 bigone 绑定功能都会取消和隐藏。

用户头像在 App 不显示，请问是 IOS 还是 Android？

**Comment by ryanhoo** [comment]
@huoguanghua BigONE 平台不对外提供 ID，这个功能将会取消。
