### ISSUE TITLE
[网站]保存二维码图片，图片命名过于简约

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#138]
### BUG 信息

BUG 描述（必填）：[网站]保存二维码图片，图片命名过于简约

BUG截图：

复现步骤：
**背景是，想要把文章发布到其它内容平台并想要附带二维码，需要下载图片并上传。
1、保存任意一篇文章的签名二维码图片，观察图片文件的名字
2、文件名为《下载.png》

预期实现：用该文章的时间戳信息或当前系统的时间戳作为图片文件命名都OK**

复现频次：总是

测试版本：总是

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by raimonfuns** [comment]
已优化，会在下个版本迭代上线。
