### ISSUE TITLE
无法识别本地相册二维码，版本号2.0.0（2）

### ISSUE THREAD

**Issue by hongxiaojun** [Press-One/issues#139]
### BUG 信息

BUG 描述（必填）：无法扫描识别本地二维码

BUG截图：

复现步骤：扫码——相册——完成——提示无法识别

复现频次：多次

测试版本：2.02

测试环境：iphone x  11.4.1（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：34855（用于发放奖励）

**Comment by ElvisZP** [comment]
@hongxiaojun 
你好，请问能够提供扫描的图片吗？

**Comment by hongxiaojun** [comment]
ElvisZP <notifications@github.com>于2018年7月30日 周一13:04写道：

**Comment by ElvisZP** [comment]
@hongxiaojun 抱歉，没有看到图片，如果您方便，麻烦上传一下您扫描失败的图片。

**Comment by hongxiaojun** [comment]
刚刚邮件附件发您啦，就是张三九定投定抛文章的二维码，我保存本地后，通过相册本地识别，提示无法识别。识别原图附件

ElvisZP <notifications@github.com>于2018年7月30日 周一13:12写道：

**Comment by ElvisZP** [comment]
@hongxiaojun 邮件回复这个可能看不到，能否给我的邮箱发这张图片？谢谢
zhangpengtongxue@gmail.com.

**Comment by ElvisZP** [comment]
已修复，等新版本发布。 
@hongxiaojun 

Mixin ID: 34855
奖励：10 PRS

**Comment by hongxiaojun** [comment]
Thanks

ElvisZP <notifications@github.com>于2018年7月30日 周一18:48写道：
