### ISSUE TITLE
登录界面密码匹配时仍显示密码不匹配

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#14]
【bug标题】登录界面密码匹配时仍显示密码不匹配

【测试版本】 http://dev.press.one/sign-up

【测试环境】所有

【复现频次】总是复现

【复现步骤】 
1 进入界面后直接点击创建账号按钮，此时提示Password not match.
2 输入正确的邮箱密码，此时Password not match.没有消失

【bug截图】
![default](https://user-images.githubusercontent.com/7984510/38840449-42542074-4212-11e8-93de-b08bd156149d.gif)

-【备注】

**Comment by raimonfuns** [comment]
已优化
