### ISSUE TITLE
偶尔出现app 卡死

### ISSUE THREAD

**Issue by hongxiaojun** [Press-One/issues#140]
### BUG 信息

BUG 描述（必填）：打开app后，点击管理——设置，然后就卡住不动。长时间等待后也无响应，需要后台强制退出方可。

BUG截图：

复现步骤：是在本地相册的二维码识别失败后（“Qrcode not recognized”），再点击管理——设置后出现的一次卡死状态

复现频次：偶尔

测试版本：2.0.0（2）

测试环境：iPhone x 11.4.1（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：34855（用于发放奖励）

**Comment by ElvisZP** [comment]
问题暂未重现，已经收录，之后会重点测试。谢谢反馈

**Comment by ElvisZP** [comment]
已修复，等新版本发布。
@hongxiaojun

Mixin ID: 34855
奖励：15 PRS
