### ISSUE TITLE
[Android-Minor] 文章时间显示不正确

### ISSUE THREAD

**Issue by yy307** [Press-One/issues#141]
### BUG 信息

BUG 描述（必填）：
打开我的订阅, 第一篇文章的时间显示错误
BUG截图：
![5ebb3703a1e1e9bb6d3b79eed424c552](https://user-images.githubusercontent.com/314256/43206162-a2750250-9057-11e8-8a9a-40c724620f8c.jpg)

复现步骤：
不可复现
复现频次：
无
测试版本：
Android版2.1.3.718

测试环境：（设备型号、系统版本、网络等）
设备:MI 6
版本:MIUI10.8.7.12开发版

**Comment by ryanhoo** [comment]
时间解析的线程不安全问题引起，已修复。
