### ISSUE TITLE
[网站]task admin系统已发放奖励显示数额不对

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#142]
### BUG 信息

BUG 描述（必填）：]task admin系统已发放奖励显示数额不对

BUG截图：
![image](https://user-images.githubusercontent.com/31027645/43240379-d3b38b90-90c8-11e8-8f51-33c03491a230.png)

复现步骤：

当前仅显示了该分页的奖励数额，没有把该任务的所有已发放奖励数额加和

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by imeoer** [comment]
@liujuanjuan1984 已确认并已修复该问题，非常感谢反馈。
