### ISSUE TITLE
[网站]task admin系统，已有任务没有显示在任务列表分页中

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#144]
### BUG 信息

BUG 描述（必填）：task admin系统，已有任务没有显示在任务列表分页中
1、选中单个项目
2、点选任务列表分页
3、在已有3个任务的情况下，该任务列表分页依然显示为空，如截图所示
预期表现：正常显示所有任务

BUG截图：
![image](https://user-images.githubusercontent.com/31027645/43354694-8b5da580-9283-11e8-8b4a-488369e2d7e0.png)

复现步骤：

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）pc，chrome

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by imeoer** [comment]
@liujuanjuan1984 经调查是功能迭代时产生的问题，已修复，非常感谢本次反馈。
