### ISSUE TITLE
[ios app]加粗的markdown语法未能支持

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#145]
### BUG 信息

BUG 描述（必填）：加粗的markdown语法未能支持
同一篇文章，在浏览器中能正常显示加粗效果
而在ios app中未支持，如截图所示

文章链接：https://press.one/file/v?s=ad33efe637ef71671833e2a4b3bec11a9b8ba4a78cc5cae3e24fe92bfcb4a8c1628c316141ac3105789e291f8393b89cce1d040ee4f4ca4306d0497d81a962b40&h=bd5f28253507efb6679674d9807008aacc9344237d2f03ac9d6c3d3c8498260f&a=f696ffeb49cce1907bebb61e741a61758948d939&f=P1&v=2

BUG截图：
![image](https://user-images.githubusercontent.com/31027645/43354757-767e7bde-9284-11e8-9d6d-63d64ab0d21e.png)
![image](https://user-images.githubusercontent.com/31027645/43354758-7b99eaae-9284-11e8-8e15-31db746bf744.png)

复现步骤：

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by ElvisZP** [comment]
已经修复上线
