### ISSUE TITLE
 草稿保存后，不生效

### ISSUE THREAD

**Issue by yulinliujian** [Press-One/issues#146]
### BUG 草稿保存后，草稿箱里仍然显示保存不成功

BUG 描述（必填）：
点击草稿保存后，草稿箱里仍然显示保存不成功
BUG截图：
![1](https://user-images.githubusercontent.com/29038837/43357425-e6635594-92b3-11e8-9d4c-6e04a9c7ce4a.png)
![2](https://user-images.githubusercontent.com/29038837/43357426-e9144bd6-92b3-11e8-95a8-9d65a9ca2256.png)

复现步骤：

复现频次：
必现

测试版本：

测试环境：（设备型号、系统版本、网络等）
wind7 64bit 谷歌浏览器
备注：

### 附加信息

Mixin ID：（用于发放奖励）
20771

**Comment by raimonfuns** [comment]
@yulinliujian  已修复。
Mixin ID: 20771
奖励：5 PRS
