### ISSUE TITLE
微信扫码识别跳转到app后请求超时

### ISSUE THREAD

**Issue by hongxiaojun** [Press-One/issues#148]
### BUG 信息

BUG 描述（必填）：

BUG截图：

复现步骤：微信朋友圈照片——使用Safari打开——跳转到app，然后一直转圈，无法打开对应文章。手机网络没问题，订阅和自己文章浏览都这正常。

复现频次：多次重现

测试版本：2.0.1（2）

测试环境：（设备型号、系统版本、网络等）iPhone x iOS11.4.1，Wi-Fi和4g都试过，开了VPN ，
延迟23ms

备注：
![fullsizeoutput_1f59](https://user-images.githubusercontent.com/35869352/43469671-48d21c26-9519-11e8-8783-13320b4c40cb.jpeg)

![img_7706](https://user-images.githubusercontent.com/35869352/43469567-0b1dd244-9519-11e8-8180-72c85e4eacea.JPG)

### 附加信息

Mixin ID：34855（用于发放奖励）

**Comment by raimonfuns** [comment]
@hongxiaojun 这是因为当时系统不稳定，请求没有及时处理。现在已修复，多谢反馈。

Mixin ID：34855
奖励：5PRS
