### ISSUE TITLE
个人信息中，添加身份职位失败

### ISSUE THREAD

**Issue by hongxiaojun** [Press-One/issues#149]
### BUG 信息

BUG 描述（必填）：

BUG截图：
![fullsizeoutput_1f55](https://user-images.githubusercontent.com/35869352/43469794-91c67e40-9519-11e8-959b-3f60dedfb494.jpeg)
![fullsizeoutput_1f5a](https://user-images.githubusercontent.com/35869352/43470085-4f97d9c8-951a-11e8-83ee-fb4f96f129e8.jpeg)

复现步骤：

复现频次：7月31日晚上23:23-23:30测试，多次出现

测试版本：2.0.1（2）

测试环境：（设备型号、系统版本、网络等）iPhonex iOS11.4.1 Wi-Fi 和4g  vpn

备注：

### 附加信息

Mixin ID：34855（用于发放奖励）

**Comment by raimonfuns** [comment]
@hongxiaojun 这是因为当时系统不稳定，请求没有及时处理。现在已修复，多谢反馈。

Mixin ID：34855
奖励：5PRS
