### ISSUE TITLE
设置头像时，上传文件不是图片未给与错误提示

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#15]
【bug标题】设置头像时，上传文件不是图片未给与错误提示

【测试版本】http://dev.press.one/wizard

【测试环境】所有

【复现频次】总是复现

【复现步骤】 
1 在设置头像这一步骤是上传dll文件，界面无反应

【bug截图】

![up-dell_file-will-not-warn](https://user-images.githubusercontent.com/7984510/38840657-4e1b1a7e-4213-11e8-9407-cdec2a1efe98.gif)

-【备注】

**Comment by liujuanjuan1984** [comment]
应该检查文件类型，并提示文件类型

另外，图片文件大小不知道有没有限制

**Comment by raimonfuns** [comment]
已修复
