### ISSUE TITLE
[网站]task admin展示我的任务时，希望添加所属项目

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#150]
### BUG 信息

BUG 描述（必填）：task admin展示我的任务时，希望添加所属项目
拓荒者每期任务会有重名任务，比如管理微信群每期都会有，但领取任务的人查看“我的任务”，却无法查看该任务属于哪个项目，容易混淆

期望：在[我的任务] 页面查看[任务列表]时，新增显示该任务所属的项目名称

BUG截图：

复现步骤：

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by imeoer** [comment]
@liujuanjuan1984 非常好的建议，会在接下来的迭代中考虑支持。

**Comment by imeoer** [comment]
@ryanhoo @Xiqiao @Chao2015cc 这个改进已经更新了，所属的账户名称改为了所属的项目名称。
