### ISSUE TITLE
[platform-bug level] short bug description

### ISSUE THREAD

**Issue by hongxiaojun** [Press-One/issues#151]
### About Bug

BUG Description (Required):

BUG Screenshots:见附件

Reproduce Steps:我的订阅——prs拓荒者基金《本次推荐30名内容创作者》，点击文章中各作者的主页链接，无法打开对应作者主页

Frequency:

App Version:2.0.1(2)

Environment: (device model, system version, network, etc)iPhone x iOS11.4.1

Note:

### Other

![fullsizeoutput_1f98](https://user-images.githubusercontent.com/35869352/43720662-4fd137e2-99c3-11e8-8f23-1a25ba96d5c4.jpeg)

![img_7794](https://user-images.githubusercontent.com/35869352/43721099-7a26ec20-99c4-11e8-8867-2056f1ebcbea.JPG)

Mixin ID: (for receiving PRS reward)
34855

**Comment by ElvisZP** [comment]
已修复，等新版本发布。
@hongxiaojun 

Mixin ID: 34855
奖励：10 PRS
