### ISSUE TITLE
复制全文➕签名，出现出错，粘贴只有签名

### ISSUE THREAD

**Issue by hongxiaojun** [Press-One/issues#153]
### BUG 信息

BUG 描述（必填）：Chrome浏览器创建完数字签名后，复制全文➕签名，出现出错，粘贴只有签名

BUG截图：
![sgwfsdghqew0jtrn5b8c q](https://user-images.githubusercontent.com/35869352/43933930-0223c316-9c7f-11e8-9e26-d169e81439be.jpg)
![epmglaxrrneeajvnhpu6aq](https://user-images.githubusercontent.com/35869352/43933931-0281074c-9c7f-11e8-889f-4f65030ab4d1.jpg)
![40qskp4ys3cvlspa09cqew](https://user-images.githubusercontent.com/35869352/43933932-02e04b4e-9c7f-11e8-841a-2610ff979fa1.jpg)
![5fqczjthrpmtvgppc0bxbw](https://user-images.githubusercontent.com/35869352/43933934-033e6a4e-9c7f-11e8-9f09-797e821b8e48.jpg)

复现步骤：Chrome浏览器打开网页版，编辑完文字，创建完数字签名后，复制全文➕签名，出现出错，粘贴只有签名

复现频次：多次

测试版本：网页版press.one

测试环境：（设备型号、系统版本、网络等）MacBook air 最新系统 wifi

备注：

### 附加信息

Mixin ID：34855

（用于发放奖励）

**Comment by raimonfuns** [comment]
@hongxiaojun 已修复，多谢反馈。

Mixin ID：34855
奖励：8 PRS
