### ISSUE TITLE
英文版本网站显示内容时，最下面的二维码下方显示为中文

### ISSUE THREAD

**Issue by bryanzk** [Press-One/issues#154]
### BUG 信息

BUG 描述（必填）：
使用PRESS.one 官方英文账号创建文件并签名，成功后，最下面的二维码下方仍然显示中文。
地址如下：
https://press.one/file/preview?s=ac3f1f93e8ceb17bac0743176a3444372042dc69b0d7c0ed453cb66c2154c51d1a1b6c73e07213cb49d22c47c3c1e5cbaad928e4653388c4f91391c6da0d88c51&h=d7904bc25c19297fe6d9a515d291df49bdc1e67bbdfd06426d2dc50fce36e66e&a=0edff29904ae7ac881c34b7f3f6334b2a72dd5b5&v=2&f=P1

现在直接点击上面的链接，显示是英文没有问题。
在同一个签名成功的窗口里刷新之后，显示是英文没有问题。

BUG截图：
![image](https://user-images.githubusercontent.com/156375/43921633-4e0f335e-9bea-11e8-95b0-9867ffd80c6f.png)

复现步骤：
只需签名即可。

复现频次：
1次

测试版本：
PRESS.one web版本

测试环境：（设备型号、系统版本、网络等）
操作系统： Mac OS X High Sierra
浏览器：Chrome Version 68.0.3440.106 (Official Build) (64-bit)

备注：

### 附加信息

Mixin ID：（用于发放奖励）
37152667

**Comment by raimonfuns** [comment]
@bryanzk  二维码的语言版本是由当前用户选择的语言环境决定的。

![image](https://user-images.githubusercontent.com/8716838/44259450-16df2a00-a244-11e8-82f5-38916c60e113.png)
