### ISSUE TITLE
文章在Android客户端中不显示图片

### ISSUE THREAD

**Issue by bryanzk** [Press-One/issues#155]
### BUG 信息

BUG 描述（必填）：
昨天在PRESS.one official账号更新了文章，今天在安卓客户端中打开文章，看不到文章中的图片，但在桌面web中没有问题。

文章链接：
https://press.one/file/preview?s=23e9de1724fe8395239ca4e481f981fccbf23dd14280f00ae70f86230b4158f9b5feb80fb97c36628a3b724ec3f09948680fd802b2ed609bbf8661429057ee311&h=d0bd9006e89d68336a479ccef3d7b27fe737191bf97d7bbd864a6e5189ac339d&a=0edff29904ae7ac881c34b7f3f6334b2a72dd5b5&v=2&f=P1

BUG截图：
![image](https://user-images.githubusercontent.com/156375/43968015-ee98b8b4-9c93-11e8-8e5d-229ae95c89ad.png)

复现步骤：
安卓客户端中扫码文章的qr码，打开后不显示图片

复现频次：
1

测试版本：
![image](https://user-images.githubusercontent.com/156375/43968150-4b8e3f4e-9c94-11e8-8129-680f001625dd.png)

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）
37152667

**Comment by ryanhoo** [comment]
新版本已经支持图文混排，请前往 Google Play 更新。
