### ISSUE TITLE
Firefox中查看英文文章单词断行

### ISSUE THREAD

**Issue by bryanzk** [Press-One/issues#156]
### BUG 信息

BUG 描述（必填）：
在Firefox中查看文章，发现右侧单词有折行情况，在chrome中没有该问题。
例如该链接中的文章： https://press.one/file/preview?s=ac3f1f93e8ceb17bac0743176a3444372042dc69b0d7c0ed453cb66c2154c51d1a1b6c73e07213cb49d22c47c3c1e5cbaad928e4653388c4f91391c6da0d88c51&h=d7904bc25c19297fe6d9a515d291df49bdc1e67bbdfd06426d2dc50fce36e66e&a=0edff29904ae7ac881c34b7f3f6334b2a72dd5b5&v=2&f=P1

BUG截图：
![image](https://user-images.githubusercontent.com/156375/43978518-87c95716-9cb5-11e8-8e19-5ce157035a0d.png)

复现步骤：
只需查看文章即可。

复现频次：
4

测试版本：
Web版

测试环境：（设备型号、系统版本、网络等）
![image](https://user-images.githubusercontent.com/156375/43978492-69662470-9cb5-11e8-89bc-6f4467ef3e2b.png)

备注：

### 附加信息

Mixin ID：（用于发放奖励）
37152667

**Comment by raimonfuns** [comment]
已修复
