### ISSUE TITLE
上传本地签名图片时，如果一开始未填标题，后来再填，仍然出现未填标题的提示信息，导致无法提交上传

### ISSUE THREAD

**Issue by bryanzk** [Press-One/issues#159]
### BUG 信息

BUG 描述（必填）：

先上传图片，直接提交，无法成功，出现“需要标题“的提示信息，写好标题后，再提交，还是失败，提示信息继续出现，导致无法上传。

BUG截图：
![image](https://user-images.githubusercontent.com/156375/44214525-60dde800-a13e-11e8-928b-fbbd3907324f.png)

复现步骤：
上传图片即可

复现频次：
3

测试版本：
https://stage.press.one/editor

测试环境：（设备型号、系统版本、网络等）
https://stage.press.one/editor

备注：

### 附加信息

Mixin ID：（用于发放奖励）
37152667

**Comment by wuhaoa** [comment]
resolved
