### ISSUE TITLE
添加个人网站的身份认证时，没有点击复制签名，仍可以继续下面的流程

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#16]
【bug标题】添加个人网站的身份认证时，没有点击复制签名，仍可以继续下面的流程

【测试版本】http://dev.press.one/main/p/4072114bf728827e911a1be6b11ef6274955ac77

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 在个人主页点击左侧添加个人认证的加号按钮
2 选个人网站，点击确认选择
3 在“添加身份认证”跳到第2步骤，写入https://www.google.com
4 在“添加身份认证”跳到第3步骤   直接选择确定

我认为如果没有点击第一步的复制签名，就不应该进入第二步骤
如果没有输入第2步的地址，就不应该进入第三步骤

【bug截图】
![confirm-self-artical](https://user-images.githubusercontent.com/7984510/38841091-49dd6f5a-4215-11e8-94b0-9e1a955635cf.gif)

-【备注】

**Comment by raimonfuns** [comment]
已优化
