### ISSUE TITLE
建议：登录PRESS.one之后，再打开其他账号的PRESS.one签名链接，不再需要登录

### ISSUE THREAD

**Issue by bryanzk** [Press-One/issues#163]
### BUG 信息

BUG 描述（必填）：
使用我自己的PRESS.one账号登录后，如果在其他地方点击PRESS.one 的内容签名链接，重新打开的浏览器页面里，如果想要订阅该内容签名的作者或其他相关操作，还得重新登录，登录之后就离开之前打开的页面了，从而降低了用户订阅的可能性，不利用扩大平台内容生态。

BUG截图：

复现步骤：

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by bryanzk** [comment]
目前在Android的客户端中也是这样，打开文章中的链接，如果指向的是 PRESS.one 平台上的页面，打开后的链接里面还是处于非登录状态。

**Comment by Xiqiao** [comment]
改版后的登录注册系统解决了session。
