### ISSUE TITLE
pressone草稿箱使用问题

### ISSUE THREAD

**Issue by jianzhifeng** [Press-One/issues#167]
### BUG 信息
该草稿不存在

BUG 描述（必填）：编辑多次后的草稿箱内文章，再次编辑时弹出“该草稿不存在”提示，页面下方只有“创建为数字签名”按钮，没有“更新草稿”按钮。

BUG截图：

复现步骤：点击草稿箱“所有草稿”，点击“编辑”

复现频次：每次都是这样

测试版本：网页端（2018.9.19）

测试环境：（设备型号、系统版本、网络等）macbook pro（13inch mid2012）
macOS sierra version10.12.3
中国联通宽带

备注：

### 附加信息

Mixin ID：（用于发放奖励）24820

**Comment by raimonfuns** [comment]
@jianzhifeng  已修复

Mixin ID：24820
奖励：5 PRS
