### ISSUE TITLE
创建合约时，输入负数价格，无法提交，同时无提示

### ISSUE THREAD

**Issue by bryanzk** [Press-One/issues#168]
### BUG 信息

BUG 描述（必填）：
创建合约时，在金额中输入“-100”，当时无出错提示。但在输入密码提交时，无反应，反复点击提交，仍然无反应，也无任何提示。回去修改金额，提交成功。
BUG截图：

复现步骤：

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）
stage.press.one
备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by raimonfuns** [comment]
已禁止输入负数
