### ISSUE TITLE
创建合约时，合约定价无验证

### ISSUE THREAD

**Issue by bryanzk** [Press-One/issues#169]
### BUG 信息

BUG 描述（必填）：
定价可以输入“33-5”，无验证出错提示，提交时无反应。跟上一个issue的情况一样。
BUG截图：
![image](https://user-images.githubusercontent.com/156375/45823452-bbc5aa80-bcbb-11e8-9625-b0f59178fde2.png)

复现步骤：

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by raimonfuns** [comment]
已优化
