### ISSUE TITLE
新建内容签名-填写文章来源无字数限制

### ISSUE THREAD

**Issue by jadylotus** [Press-One/issues#17]
【bug标题】新建内容签名处文章来源无字数限制
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1、登录帐号
2、新建内容
3、填写文章来源，无字数限制
4、造成结果：由于复制粘贴错误，我将整个文章内容复制粘贴到了文章来源处，文章太长，框选删除会浪费大家的时间
【bug截图】
【备注】

**Comment by liujuanjuan1984** [comment]
我发现但凡是输入框，都没有一个比较符合使用情境的长度限制。

**Comment by virushuo** [comment]
没限制的原因是最终链上是靠链本身的经济系统来限制过长的，因为所有东西都开源之后没法控制别人跳过代码的限制。不过暂时这个阶段还是应该加上这些限制的，先标记成bug了。

**Comment by raimonfuns** [comment]
已修复
