### ISSUE TITLE
[web]登录A帐号后，再登录B帐号出现登录状态错误

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#170]
### BUG 信息

BUG 描述（必填）：登录A帐号后，再登录B帐号出现登录状态错误

BUG截图：

复现步骤：
1、已登录PRS拓荒者基金帐号，并打开多个tab页面。所有操作及表现都正常
2、然后，打开新的tab，并登入了我的个人帐号。
3、在刚才基金帐号打开的那些页面刷新，显示了我的个人帐号已登入。尝试以下操作时，遇到问题：
3.1 个人帐号，点击基金帐号的【项目6期】，会直接跳转到 个人主页，而非项目内页
3.2 我在个人主页，粘贴任务地址（ https://press.one/main/p/e0b2908b00ecc554e460863ee43481b8d47e8641/projects/14/tasks/48 ）并跳转，也会刷新到我的个人主页，而非进入到任务页面
3.3 我在这个人的文章页面，赞赏他，点击确认后，背景页面也直接跳转到我个人主页。
![photo_2018-09-21_11-47-01](https://user-images.githubusercontent.com/31027645/45861518-901bf080-bd9f-11e8-89a5-f0349472a4e8.jpg)

4、当我关掉所有PRS页面，新打开tab，登入我个人帐号再重复以上操作，则一切正常。

复现频次：总是

测试版本：https://press.one/

测试环境：（设备型号、系统版本、网络等）windows，chrome

备注：应该和登录状态有关

### 附加信息

Mixin ID：（用于发放奖励）无需奖励

**Comment by Leask** [comment]
这个是之前登录信息没清除的问题，我记得已经修了。 cc @raimonfuns
