### ISSUE TITLE
[web]task admin批量核准奖励时，单人奖励无法输入0

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#171]
### BUG 信息

BUG 描述（必填）：task admin批量核准奖励时，单人奖励无法输入0

BUG截图：
![image](https://user-images.githubusercontent.com/31027645/45863508-11c44c00-bda9-11e8-9654-f5a88ffa1675.png)

复现步骤：
1、批量核准奖励界面，单人奖励尝试输入0，提示必须大于等于0，但实际上无法提交0
预期实现：有时完成任务的人未满足任务要求，奖励是0，期望这里能支持0奖励

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

**Comment by imeoer** [comment]
看起来是 `poMoneyInput` 指令不允许为 0 的问题。 @raimonfuns

**Comment by raimonfuns** [comment]
@liujuanjuan1984 @imeoer 已修复~
