### ISSUE TITLE
[web]通过app提交的图片签名，预览正常，但在网页端查看详情则倒过来了

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#172]
### BUG 信息

BUG 描述（必填）：[web]通过app提交的图片签名，在网页端查看倒过来了

BUG截图：

复现步骤：
1、手机拍照，并通过ios app创建图片签名，能正常显示（预览和点开都正常）
2、在web端查看该图片签名，预览正常，点开看则图片横过来了

注：图片是采用ios手机 1：1拍的正方形

https://press.one/file/preview?s=bc4fc7ab9c81cb395419a03e683063eeb2ee2876c24d7bac6dc63ae7e21abdc47974b1110eb2a2d061bb631fc34cc67507636665972da9d74851486fc86718fd00&h=cf684d31f691449d8b2795b99889cd3f16acc9f89d37ed22c8b4c6c8083ae412&a=ed73e900e209def08ff03a2e3fadbac99af087c0&v=2&f=P1

帐号：行动的女巨人

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by imeoer** [comment]
看起来上传的图片丢失了一些 EXIF 信息，iOS 端可能在图片上传前做过图片处理。

**Comment by raimonfuns** [comment]
已修复~
