### ISSUE TITLE
[web]引用用户X的图片，会弹出来赞赏用户Y的窗口

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#173]
### BUG 信息

BUG 描述（必填）：[web]引用用户X的图片，会弹出来赞赏用户Y的窗口

BUG截图：

复现步骤：
1、个人帐号，赞赏了几篇文章，最后一次是赞赏用户Y的文章
2、然后尝试发布一篇文字内容，并引用了用户X的图片；在签发该内容时，弹窗下图所示，提示赞赏用户X：
![image](https://user-images.githubusercontent.com/31027645/46186493-7df70080-c311-11e8-8072-5fd57afaf445.png)
如果是点击跳过，此时输入密码，正常发布。
如果是点击已赞赏发布签名，则此时输入密码文章正常发布，但同时弹出一个赞赏页面，但**提示赞赏的是我最近一次赞赏的用户Y，即不是我引用的那个图片的作者X**
（测试几次都如此）
![image](https://user-images.githubusercontent.com/31027645/46186579-fb227580-c311-11e8-9e85-1417795cbaf0.png)

3、

复现频次：总是

测试版本：windows，chrome，web

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by raimonfuns** [comment]
发布签名内容之后，会弹出赞赏窗口，是属于误触发。已修复。
