### ISSUE TITLE
[web]创建完合约后跳转的页面，提供了自己订阅自己的功能

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#176]
### BUG 信息

BUG 描述（必填）：创建完合约后跳转的页面，提供了自己订阅自己的功能

BUG截图：

![image](https://user-images.githubusercontent.com/31027645/46253064-a0218780-c4a5-11e8-929a-e1317d7a3ebf.png)
![image](https://user-images.githubusercontent.com/31027645/46253077-d232e980-c4a5-11e8-875f-4adf5b97e072.png)
![image](https://user-images.githubusercontent.com/31027645/46253085-e4148c80-c4a5-11e8-9704-c0d7e31e9596.png)
![image](https://user-images.githubusercontent.com/31027645/46253087-e7a81380-c4a5-11e8-8698-4dec78118a93.png)

复现步骤：
1、给自己的内容创建完合约后，跳转到如图所示页面
2、点击订阅，导致自己订阅了自己

复现频次：

测试版本：beta.press.one

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by raimonfuns** [comment]
已修复
