### ISSUE TITLE
官网keystore可用于开发网直接登录，但个人信息又可重新设置

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#18]
【bug标题】官网keystore可用于开发网直接登录，但个人信息又可重新设置
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.在官网创建了一个页面https://press.one/main/p/6567376060ddafe64a951523c8a39bc137b24335 保存了keystore
2. 在开发网站 用keystore 可以直接登录，但需要重新设置名字，头像等个人信息 ，最终生成的页面为 http://dev.press.one/main/p/6567376060ddafe64a951523c8a39bc137b24335
3.为什么官网的keystore可用于开发网站的登录？但个人信息等又是不同的，需要重新设置？
【bug截图】
【备注】

**Comment by virushuo** [comment]
这个是正常的，自己保存的keystore就是私钥，用它就可以签名各种消息。在测试服务器上“重新设置名字头像”实际上就是 签名->保存 的过程。这就意味着测试服务器没有你的具体信息，你重新设置了一份（等同于注册）。

目前其实不用pressone生成，用标准以太坊钱包的keystore也是可以签名和完成设置的。
