### ISSUE TITLE
beta版无法正常添加身份证明

### ISSUE THREAD

**Issue by Galaxy1227** [Press-One/issues#181]
### BUG 信息

BUG 描述（必填）：在beta版添加微博身份证明时，提示“无法找到这条身份验证信息的签名者。”
添加Iveryone身份被证明时，网页跳转出错，提示：{"errno":4000,"errmsg":"appkey\u9519\u8bef","time":1538287939,"data":{}}

后来又试了Twitter和Github，都无法正常绑定。应该所有的都有问题。

BUG截图：
![image](https://user-images.githubusercontent.com/39395508/46253899-1ed3f000-c4b9-11e8-8957-60aef1c08c05.png)

![image](https://user-images.githubusercontent.com/39395508/46253957-39f32f80-c4ba-11e8-8029-2029f95d0bb5.png)

复现步骤：规律复现，非偶然情况

复现频次：每一次

测试版本：beta版

测试环境：（设备型号、系统版本、网络等）华为Matebook，Win10，WIFI网络

备注：

### 附加信息

Mixin ID：（用于发放奖励）36477487

**Comment by Galaxy1227** [comment]
应该是所有身份证明都无法正常添加，Github，Twitter也都不行。

**Comment by Leask** [comment]
已经修复。
