### ISSUE TITLE
[web]已购买的合约，关联合约页面没显示

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#182]
### BUG 信息

BUG 描述（必填）：已购买的合约，关联合约页面没显示

BUG截图：
![image](https://user-images.githubusercontent.com/31027645/46254168-75dbc400-c4bd-11e8-855c-383471000bb6.png)

复现步骤：
1、如图所示，购买了该文章的合约
2、但再次查看该文章（或sh刷新，或重新打开），此处依然是默认显示，没有显示本人是否已购买该授权

期望表现：如果打开的是已购买的合约，能显示已购买。

复现频次：

测试版本：beta

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by raimonfuns** [comment]
@liujuanjuan1984 如果已经购买，用途上面显示「你已在 2018-09-30 xx:xx:xx 购买过此合约」。
按钮之所以还显示「购买」，是因为将来有些合约是允许重复购买的，所以在这里不限制。
