### ISSUE TITLE
[web]合约小额支付，是否可以免密？

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#183]
### BUG 信息

BUG 描述（必填）：合约小额支付，是否可以免密？

BUG截图：

复现步骤：
1、目前所有的合约支持，都需要输入密码
2、是否可以和赞赏相似，小额支付免密？

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by raimonfuns** [comment]
@liujuanjuan1984 合约的购买和赞赏有一点不同，合约的数据需要上链，所以一定得用户输入一次密码。
