### ISSUE TITLE
[ios]查看我的内容合约时，已产生交易次数没有刷新

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#184]
### BUG 信息

BUG 描述（必填）：查看我的内容合约时，已产生交易次数没有刷新

BUG截图：

复现步骤：
1、在ios app点击【我的签名】，选择一篇已产生交易的内容打开
2、在该文章详情，点击【已关联合约[购买授权]】，弹出一个半屏幕页面
3、该半屏页面显示 用途的地方，关于【已产生0次交易】这里总是0次，其实已经有交易产生了

复现频次：总是
测试版本：2.0.2(24)

测试环境：（设备型号、系统版本、网络等）ios test

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by ElvisZP** [comment]
已修复
