### ISSUE TITLE
[ios]查看他人交易合约详情，已交易次数显示不正确

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#185]
### BUG 信息

BUG 描述（必填）：

BUG截图：

复现步骤：
1、点击1篇他人的文章
2、点击该文章的已关联合约
3、在弹出的半屏页面上点击【查看合约详情】
4、查看累计收入区域，总是显示【共产生5次交易】，但该文章的实际交易次数可能是4次，也可能是7次

帐号：002@juanjuan.com
查看文章： 刘胜新《为什么PRESSone不建设在EOS上》，真实7次，但显示5次
查看文章：郑成文《如何提高自己的执行力》，真实4次，但显示5次

复现频次：

测试版本：2.0.2（24） ios test

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by ElvisZP** [comment]
已修复
