### ISSUE TITLE
[web]合约价格设置为0.0001，提示invalid contract code

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#188]
### BUG 信息

BUG 描述（必填）：

BUG截图：
![image](https://user-images.githubusercontent.com/31027645/46255277-b3e0e400-c4cd-11e8-8ad1-6e9605db4874.png)

复现步骤：
1、添加合约时，设置价格为0.0001（即小数位超过3位），能正常输入
2、点击【确认创建】并输入密码后，提示invalid contract code

预期表现：小数位超过3位时，客户端就有提示（比如在赞赏输入时就有这个判断）；服务器返回的提示信息更清晰一些，比如这个情况是，合约价格不能超过3位小数位

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by raimonfuns** [comment]
已修复
