### ISSUE TITLE
[web]合约价格设置超大额，实际价格被篡改了

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#189]
### BUG 信息

BUG 描述（必填）：

BUG截图：

复现步骤：
1、给自己的内容添加合约时，设置价格为 12345678901234567890
2、成功发布
3、但发布后的价格变成了 12345678901234567000 CNB  
4、ios端显示的也变了，但变成了 12345678901234567168  CNB

帐号 002@juanjuan.com

预期实现：
1、最大数值建议弄小点。比如最大9位数?
2、但我已设置的这个数值，为什么被“篡改”了？

复现频次： 测试了2次都如此

测试版本：beta 

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by raimonfuns** [comment]
已经限制了最大的金额输入 88888888。也就不会出现数字溢出的问题。
