### ISSUE TITLE
为单篇文章「添加合约」时，交易内容没有自动补全，仍需要手动选择

### ISSUE THREAD

**Issue by bhuazh** [Press-One/issues#191]
### BUG 信息
BUG 描述（必填）：
为单篇文章「添加合约」时，交易内容没有自动补全，仍需要手动选择

1. 这个步骤是多余
2. 当文章非常多时，手动选择是困难的

BUG截图：
![image](https://user-images.githubusercontent.com/2714028/46258352-c83bd580-c4fb-11e8-8256-ff033781adf5.png)

![image](https://user-images.githubusercontent.com/2714028/46258350-bbb77d00-c4fb-11e8-8895-e591f9de30ef.png)

复现步骤：

复现频次：必现
测试版本：Beta 版

测试环境：（设备型号、系统版本、网络等）
Chrome  浏览器

备注：

### 附加信息

Mixin ID：27299

**Comment by raimonfuns** [comment]
已修复
