### ISSUE TITLE
[web]task admin任务进度条已核准百分比有误

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#192]
### BUG 信息

BUG 描述（必填）：

BUG截图：
![image](https://user-images.githubusercontent.com/31027645/46287051-e533df80-c5b3-11e8-81d2-21020e2e061f.png)

复现步骤：
1、如图所示，已核准为绿色条，47人占总进度条100人的比例，仅有全长的30%左右；
预期表现：已核准的进度应该是全长的47%，而不是已完成的47%

复现频次：

测试版本：press.one  web

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by imeoer** [comment]
@liujuanjuan1984 感谢报告，已 fix 该问题。
