### ISSUE TITLE
WEB 端 查看合约内容后，签名内容数字按钮失效

### ISSUE THREAD

**Issue by MonsterWong** [Press-One/issues#194]
### BUG 信息

BUG 描述（必填）：WEB 端 查看合约内容后，签名内容数字按钮失效，按动无反应。

BUG截图：
![error 02](https://user-images.githubusercontent.com/40250312/46383902-1b0bbd80-c6b3-11e8-9d5a-32a0ba75f821.jpg)

复现步骤：登录状态下查看任意自己创建的合约，合约打开后，左侧的签名内容数字按钮即失灵，无法跳转。

复现频次：100%

测试版本：web

测试环境：（设备型号、系统版本、网络等）
window 7，chrome浏览器，最新版
备注：

### 附加信息
猜测跟我的上一条issue #193 应该是相同根源导致

Mixin ID：（用于发放奖励）
34305390

**Comment by wuhaoa** [comment]
resolved.
