### ISSUE TITLE
点击充值，输入数量，生成的MIXIN二维码图片上出现“app logo”字体，图片显示不出来

### ISSUE THREAD

**Issue by wangshuncai** [Press-One/issues#195]
### BUG 信息

BUG 描述（必填）：点击充值，输入数量，生成的MIXIN二维码图片上出现“app logo”字体，图片显示不出来

BUG截图：
![image](https://user-images.githubusercontent.com/7950092/46795949-fb912680-cd7d-11e8-9bab-c09951338db6.png)

复现步骤：

复现频次：all

测试版本：

测试环境：smartisan M1L

备注：

### 附加信息

Mixin ID：（用于发放奖励）37154227

**Comment by Xiqiao** [comment]
这个是mixin的问题，我们无法解决

**Comment by Leask** [comment]
老的用户才有这个问题。新的用户应该不会有了。
