### ISSUE TITLE
确认创建内容前面的时候，输入错误的密码，恶意连续点击“确认提交”，要四五秒才返回密码错误

### ISSUE THREAD

**Issue by wangshuncai** [Press-One/issues#196]
### BUG 信息

BUG 描述（必填）：确认创建内容前面的时候，输入错误的密码，恶意连续点击“确认提交”，要四五秒才返回密码错误，同时确认提交按钮变白，鼠标定位输入框也暂时无法修改密码，要等待5，6秒才行，响应比较慢

BUG截图：
![image](https://user-images.githubusercontent.com/7950092/46796743-faf98f80-cd7f-11e8-9e55-ce102c1484f3.png)

复现步骤：

复现频次：all

测试版本：

测试环境：smartisan M1L

备注：

### 附加信息

Mixin ID：（用于发放奖励）37154227

**Comment by raimonfuns** [comment]
已修复

奖励：5 PRS
Mixin ID：37154227
