### ISSUE TITLE
切换成日语，很多地方没有日语化，包括点进去的一些页面

### ISSUE THREAD

**Issue by wangshuncai** [Press-One/issues#197]
### BUG 信息

BUG 描述（必填）：切换成日语，很多地方没有日语化，包括点进去的一些页面

BUG截图：
![image](https://user-images.githubusercontent.com/7950092/46797441-c2f34c00-cd81-11e8-9058-ffd61b9475b0.png)

复现步骤：

复现频次：all

测试版本：

测试环境：smartisan M1L

备注：

### 附加信息

Mixin ID：（用于发放奖励）37154227

**Comment by ryanhoo** [comment]
@wuhaoa 先把日语选项移除掉，翻译完整了再开放吧。
