### ISSUE TITLE
身份认证iveryone身份链接后点击ivery图标一直加载中

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#20]
【bug标题】身份认证iveryone身份链接后点击ivery图标一直加载中
【测试版本】all
【测试环境】pc，chrome
【复现频次】always
【复现步骤】
1.身份认证选择iveryone，完成了身份链接确认，见图1
2.在pressone页面https://press.one/main/p/6567376060ddafe64a951523c8a39bc137b24335 点击iveryone图标，跳转到https://beta.ivery.one/PersonalHome/1716556?showpressone=1
3.该页面一直显示加载中，无法正常显示，见图2
4.重开一个页面，访问iveryone网站并手工登录，无法查看到任何pressone相关信息或页面
5.在iveryone网站登录的情况下，通过pressone页面点击iveryone图标，另外一个页面打开访问iveryone，才弹出pressone的认证信息，见图3

【bug截图】
【备注】
图1-身份链接完成
![image](https://user-images.githubusercontent.com/31027645/38846980-cd276854-4231-11e8-9ef6-874304080bb8.png)
图2-
![image](https://user-images.githubusercontent.com/31027645/38847025-0798cac8-4232-11e8-810c-a90e2c9b52bf.png)
图3-
![image](https://user-images.githubusercontent.com/31027645/38847168-cf1d497a-4232-11e8-89c9-a36ab201f9dd.png)
![image](https://user-images.githubusercontent.com/31027645/38847181-e19203de-4232-11e8-9b04-9c89454f86c8.png)

**Comment by raimonfuns** [comment]
已修复
