### ISSUE TITLE
[ios]app端名字长度限制与web端不一致，比web端长很多

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#201]
### BUG 信息

BUG 描述（必填）：app端名字长度限制与web端不一致，比web端长很多

BUG截图：

复现步骤：

预期实现：多端的字数限制可以保持一致

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by ElvisZP** [comment]
已修复
