### ISSUE TITLE
[ios]点击合约详情，购买者信息不应包含profile页面链接

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#205]
### BUG 信息

BUG 描述（必填）：

BUG截图：
![image](https://user-images.githubusercontent.com/31027645/47601517-98052b00-da04-11e8-951c-3c9eff7e1dcb.png)

复现步骤：
1、账号C查看他人的合约交易详情（账号A购买了账号B的合约）
2、在合约详情页，点击交易明细，跳转到了买方的个人主页，相当于曝光了买方隐私信息

在web端，则第2步不会有任何跳转响应

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by ElvisZP** [comment]
这个之前已经修复
