### ISSUE TITLE
[ios]基金账号通过个人主页点击认领自己发布的任务，报错

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#206]
### BUG 信息

BUG 描述（必填）：

BUG截图：

复现步骤：
1、本账号A是基金账号，点击左上角头像，进入项目列表并认领一个任务
2、提示：JSON is invalid

复现频次：总是

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by imeoer** [comment]
@liujuanjuan1984 这个问题是否还存在呢 (手头暂无 iOS 设备 :() ？

**Comment by raimonfuns** [comment]
先 closed，有问题再打开
