### ISSUE TITLE
[iOS-bug 级别：轻量级] 移动端 chrome 浏览器编辑长文章内容丢失

### ISSUE THREAD

**Issue by MonsterWong** [Press-One/issues#207]
### BUG 信息

BUG 描述（必填）：手机chrome浏览器编辑草稿箱内的长文章时，出现内容丢失。

BUG截图+复现步骤：：
1. 原文章已存放于草稿箱，chrome浏览器可以正常打开看到。
![img_0080](https://user-images.githubusercontent.com/40250312/47917087-ae99ff00-dea8-11e8-812f-f30d33b3f914.PNG)

2. 直接点击编辑进入编辑器界面也能看到待编辑文稿

![img_0083](https://user-images.githubusercontent.com/40250312/47917147-dee19d80-dea8-11e8-8bf9-30a39d4c670c.PNG)

3. 此时点击”使用简版的编辑器“，文章消失

![img_0081](https://user-images.githubusercontent.com/40250312/47917191-f587f480-dea8-11e8-8d6f-672a1ff8bc9e.PNG)

4.再切换回markdown 编辑器也无法找回文章。

![img_0082](https://user-images.githubusercontent.com/40250312/47917282-4992d900-dea9-11e8-8a0a-d0f3424f245f.PNG)

复现频次：每次

测试版本： chrome 70.0.3538.75

测试环境：（iphone 8、系统版本12.0.0、LTE&WiFi ）

备注：

### 附加信息

Mixin ID：34305390

**Comment by raimonfuns** [comment]
已修复。

Mixin ID：34305390
奖励：5PRS
