### ISSUE TITLE
[Windows] 【我的订阅】文章跳转链接不正确

### ISSUE THREAD

**Issue by MonsterWong** [Press-One/issues#208]
### BUG 信息

BUG 描述（必填）：在我的订阅页面点击想要阅读的文章，页面跳转后不是直接到该文章，而是跳至文章作者的主页

BUG截图：
1. 在我的页面点击想要阅读的订阅文章
![bug 1-1](https://user-images.githubusercontent.com/40250312/48179719-c9dd9200-e320-11e8-843f-916d2b7c0273.jpg)

2. 跳转页面不是该篇文章的页面而是文章作者的主页
![bug 1-2](https://user-images.githubusercontent.com/40250312/48179735-da8e0800-e320-11e8-87f8-11453223f018.jpg)

复现步骤：如上

复现频次：每次

测试版本：Web 版

测试环境：Window 10，Chrome Version 69.0.3497.100 (Offizieller Build) (64-Bit)， Wifi

备注：

### 附加信息

Mixin ID：34305390

**Comment by raimonfuns** [comment]
@MonsterWong 收到，会尽快修复

**Comment by raimonfuns** [comment]
已修复

奖励：10PRS
Mixin ID：34305390
