### ISSUE TITLE
[android]锤子手机分享自己创建的文章时，会闪退回文章列表界面

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#209]
### BUG 信息

BUG 描述（必填）：
分享自己创建的文章时，会闪退回文章列表界面。
录屏演示: https://imgur.com/a/BS1uU6z

手机: 锤子坚果

by yc 通过PRS拓荒者基金任务提交 

BUG截图：

复现步骤：

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）

**Comment by ryanhoo** [comment]
无法复现，应该是老版本的问题。
