### ISSUE TITLE
使用本地Keystore登录时，没有对邮箱进行验证

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#21]
【bug标题】使用本地Keystore登录时，没有对邮箱进行验证

【测试版本】http://dev.press.one/login

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 切换到使用本地Keystore登录
2 点击选中：我希望以后把Keystore保存在服务器......
3 输入任意字符

【bug截图】
![local-keystore-use-email-not-check](https://user-images.githubusercontent.com/7984510/38849860-342ced44-4241-11e8-9211-c0dc670c395e.gif)

【备注】

**Comment by liujuanjuan1984** [comment]
#11  

这两处都需要填写邮箱，理论上规则应该是完全一样的。
为啥注册时填写邮箱，会判断有无@符号
这里不判断呢？

**Comment by raimonfuns** [comment]
已修复
