### ISSUE TITLE
[iOS] iOS app创建合约问题

### ISSUE THREAD

**Issue by Chao2015cc** [Press-One/issues#211]
### BUG 信息

BUG 描述（必填）：创建合约提交密码时，若使用了apple钥匙串，用途1的描述会自动变为登录账号。

BUG截图：

复现步骤：创建合约，输入密码，使用iCloud钥匙串，提交。

复现频次：必现

测试版本：iOS 3.1.2（45）

测试环境：设备型号 iOS XS、系统版本 iOS 12.1、网络 4G

**Comment by ElvisZP** [comment]
已经修复，下个版本发布。
