### ISSUE TITLE
[WEB] 图片上传后显示为翻转

### ISSUE THREAD

**Issue by MonsterWong** [Press-One/issues#212]
### BUG 信息

BUG 描述（必填）：手机拍摄的竖版照片上传后被自动翻转为横板。

BUG截图：

![bug 1205](https://user-images.githubusercontent.com/40250312/49531954-bee43600-f8bb-11e8-9e43-8a4a2104e34d.jpg)

复现步骤：上传图片做头像时，在电脑中显示为竖版的照片在上传后自动翻转。

复现频次：总是

测试版本：Windows 10, Chrome, 照片为iphone拍摄

测试环境：（设备型号、系统版本、网络等）

备注：以前手机app直接发布图片时也有同样的问题，后来已经修复了。

### 附加信息

Mixin ID：34305390

**Comment by raimonfuns** [comment]
@MonsterWong 已修复
奖励：5 PRS
Mixin ID：34305390
