### ISSUE TITLE
[iOS-light] YouTube视频显示尺寸不正常

### ISSUE THREAD

**Issue by MonsterWong** [Press-One/issues#213]
### BUG 信息

BUG 描述（必填）：文章内嵌入YouTube视频后，iOS app 显示尺寸不正常，（无法完整显示）。
点击视频打开后，则可以正常播放。

web 端显示正常。

文章地址 https://press.one/file/preview/d3aede2e9eebe30d80b9f3da282f77b43ee956793f92f9cfed08debc106d8ba7

BUG截图：
![1573074775](https://user-images.githubusercontent.com/40250312/49629868-edf9c500-f9eb-11e8-9ecd-4cabe7e6aaa4.jpg)

复现步骤：

复现频次：

测试版本：iOS 3.1.2

测试环境：iPhone 8、iOS 12.1、LTE 以及wifi）

备注：

### 附加信息

Mixin ID：34305390

**Comment by ElvisZP** [comment]
已修复，下个版本发布。
