### ISSUE TITLE
赞赏显示不全，有时候就不显示。

### ISSUE THREAD

**Issue by jianmeittup** [Press-One/issues#214]
### BUG 信息

BUG 描述（必填）：赞赏给某个文章，有时候我的头像能看见，有时候在赞赏处就不显示了，出现过2次不可见情况。

BUG截图：

复现步骤：

复现频次：

测试版本：

测试环境：（设备型号、系统版本、网络等）

备注：

### 附加信息

Mixin ID：（用于发放奖励）34684196

**Comment by ryanhoo** [comment]
描述不清楚，赞赏时如果已经有三行（18 个）已赞赏的，那么不显示是正常的，如果才几个赞赏数据还没有显示，那就是 bug。
另外提 bug 的时候最好提供更详细的信息，比如 iOS/Android，系统版本、App 版本。

**Comment by jianmeittup** [comment]
只有几个赞赏，打赏之后显示也不全。不过现在没再碰到了。下次提交会信息详细的，谢谢！
