### ISSUE TITLE
新注册用户上传头像颠倒

### ISSUE THREAD

**Issue by GraceXXu** [Press-One/issues#22]
【bug标题】新注册用户上传头像颠倒
【测试版本】press.one 官网注册
【测试环境】iPhone 6s ，AT&T 
【复现频次】总是复现
【复现步骤 上传头像图片后 一直为颠倒的

**Comment by virushuo** [comment]
是在手机上直接使用页面上传吗？这个有点奇怪 @raimonfuns

**Comment by liujuanjuan1984** [comment]
我没遇到过这个情况，我这边都正常。原始图片自身就是颠倒的话，上传作头像颠倒也正常。

**Comment by raimonfuns** [comment]
iphone 手机在选择高度比宽度大很多的图片时，会出现这个颠倒的现象，正在修复中

**Comment by raimonfuns** [comment]
已修复
