### ISSUE TITLE
pictures pool for PRESSone idea pool 0403

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#223]
![post_banner](https://user-images.githubusercontent.com/31027645/55451386-442aed80-5605-11e9-9417-164827091f59.png)
![idea_pool_apps](https://user-images.githubusercontent.com/31027645/55451387-442aed80-5605-11e9-95d8-d082d8153a8c.png)
![idea_pool_newdirection](https://user-images.githubusercontent.com/31027645/55451388-442aed80-5605-11e9-8721-11afc3e3b885.png)
![idea_pool_requirement](https://user-images.githubusercontent.com/31027645/55451390-44c38400-5605-11e9-842c-3b6627658fff.png)
![idea_pool_tools](https://user-images.githubusercontent.com/31027645/55451391-44c38400-5605-11e9-8d0e-753dddc4dee8.png)

**Comment by liujuanjuan1984** [comment]
![image](https://user-images.githubusercontent.com/31027645/58860315-6c56cb80-86de-11e9-8925-22e9e8ebde26.png)

**Comment by liujuanjuan1984** [comment]
![image](https://user-images.githubusercontent.com/31027645/58860528-e4bd8c80-86de-11e9-8bf5-5cd33da94842.png)

**Comment by raimonfuns** [comment]
closed
