### ISSUE TITLE
[BASEone][用户建议]记录用户上次阅读位置

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#229]
### BUG 信息

BUG 描述（必填）：

用户“李浩天”提议：
base.one是不是可以增加记录的功能？每次进入都需要重新选择阅读的位置其实蛮尴尬的

复现频次：总是

备注：

### 附加信息

已发放 20PRS 感谢用户的建议

**Comment by ryanhoo** [comment]
已完成
