### ISSUE TITLE
登录后点击logo没有进入到个人主页

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#23]
【bug标题】登录后点击logo没有进入到个人主页

【测试版本】
个人主页
http://dev.press.one/main/p/478ef9a3d0bd5a1fa1d8154c93808230d080950e

帮助界面
http://dev.press.one/support/identity-verification

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 点击左上角logo

【bug截图】
![binding-jump-error](https://user-images.githubusercontent.com/7984510/38851010-77262a3e-4246-11e8-9536-4f705985949b.gif)

-【备注】

**Comment by virushuo** [comment]
这个就是这样设计的，不然用户就回不到首页了。首页还会发布一些信息的，所以…
