### ISSUE TITLE
[BASEone]章节内点击链接跳转到某个章节，目录没有对应跳转/刷新

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#230]
### BUG 信息

BUG 描述（必填）：
如下图所示A，在某个章节内容中点击超链接跳转到了某个章节，但左侧目录并没有相应跳转/刷新

BUG截图：
![image](https://user-images.githubusercontent.com/31027645/58791297-83d17e00-8624-11e9-83c7-2ed17c2143c1.png)

复现步骤：

复现频次：总是出现

reporter：李浩天

**Comment by raimonfuns** [comment]
已修复
