### ISSUE TITLE
[web]订阅相关功能显示错误

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#231]
### BUG 信息

BUG 描述（必填）：
当前web版本，和订阅相关的功能存在以下问题：

1、访问他人主页，没有显示订阅状态按钮
![image](https://user-images.githubusercontent.com/31027645/60002034-75faa000-969a-11e9-851a-e57416b328bb.png)

2、实际上没有订阅此人，访问该人某篇文章，依然显示为已订阅的状态
![image](https://user-images.githubusercontent.com/31027645/60002158-b3f7c400-969a-11e9-9152-d07cd71734b1.png)

3、我的订阅数量不符，实际订阅人数远超20人
![image](https://user-images.githubusercontent.com/31027645/60002231-d7227380-969a-11e9-88d3-a25e57c019e3.png)

复现频次：总是

测试版本：

备注：

**Comment by raimonfuns** [comment]
已修复
