### ISSUE TITLE
[xuecn]习题所提交的代码有误，但依然被判定通过

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#232]
### BUG 信息

BUG 描述（必填）：习题#14，处理大写的逻辑我没写（不会写），但提交运行后依然判定习题成功。涉及账号：liujuanjuan1984

---代码如下

import re

'''
利用正则表达式完成函数
将所有数字替换为空格，非数字转换为大写形式
'''

#替换数字为空格
atestStr = "asdfad23piDFADF"
pttnx = r'[0-9]'
replx = " "
aStr = re.sub(pttnx,replx,atestStr)

#数字之外全部大写【不会写】
pttny = r'[a-z]'
#reply = re.match(pttny,atestStr)
#aStr = re.sub(pttny,reply,atestStr)

print(atestStr)

**Comment by ryanhoo** [comment]
现在你所做的习题是主观题，与客观题不同的是，它没有指定的、唯一的答案，每个人的解答方法可能都不一样。主观题的目的并不是为了考察某个具体知识点，而是考察整体解决问题的能力。
如果不会做，应该去讨论、聊天中与其他人交流讨论，得出最优解。如果每个习题都写 `print('hello world')` 也能通过习题，但是要记住我们的习题等数据之后会在链上存证，作弊的行为也会被如实记录。
这个点可以作为优化提议，之后可以加入 test case 判断用户的答案是否满足各种边界条件。
