### ISSUE TITLE
首页，鼠标点击西乔漫画图片，界面闪烁无跳转

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#24]
【bug标题】首页，鼠标点击西乔漫画图片，界面闪烁无跳转

【测试版本】
http://dev.press.one/

【测试环境】所有

【复现频次】经常

【复现步骤】
1 西乔漫画图片

【bug截图】
![home-jump-error](https://user-images.githubusercontent.com/7984510/38851168-34857f58-4247-11e8-9834-b08288f9e8b5.gif)

-【备注】
gif 看着不明显，其实是存在网页闪烁的情况，并且鼠标变成了小手，让人以为可以跳转。

**Comment by virushuo** [comment]
应该去掉链接

**Comment by raimonfuns** [comment]
已修复
