### ISSUE TITLE
身份认证绑定github，每次确认选择都自动生成签名，导致重复

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#26]
【bug标题】身份认证绑定github，每次确认选择都自动生成签名，导致重复
【测试版本】all
【测试环境】pc，chrome，github已登录
【复现频次】always
【复现步骤】
1.身份认证尝试绑定github，在身份认证页面确认选择github
2.未填写任何信息时，网站已默认填写了github的签名信息！！ 
3.原来每次确认选择github后，就默认自动重新发布了签名信息！
如果在这个环节不知情或恶意暴力刷，就会刷很多条此类信息
https://gist.github.com/liujuanjuan1984

【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/38856074-fc117d64-4257-11e8-9038-d20bbd3f9d1f.png)

**Comment by virushuo** [comment]
这个似乎应该统一处理，凡是 已经有的身份重新绑定的时候都应该提示是否要覆盖之前的身份，并且要重新进行验证流程。 @Xiqiao
