### ISSUE TITLE
内容条目区域的交互响应区较多，令人混乱，对小白不友好

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#28]
【bug标题】内容条目区域的交互响应较多，令人混乱，对小白不友好
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.创建了一条内容，想要预览阅读该页面，完全不知道该如何操作，每次都是乱点随机谈出来review页面
2.经摸索，规律是：
空白区域，点击响应打开或折叠该条目，打开后显示查看签名、复制签名、访问快照3个功能。
内容标题，点击响应打开阅读页面
箭头↑，点击响应跳转到内容的原文页面
问题在于，同一个条目区域，响应方式与入口好好几个，易混乱

3.建议：
箭头↑，跳转到原文页面，不要放在内容标题旁边；因为这个响应会和内容标题自身的响应，令人混乱。可以放到打开条目后的功能中。

内容标题打开阅读页面，建议在打开条目后的功能列表中也增加一条。

4.不考虑现有功能设计，当我点击一条内容条目时，我更愿意立即响应的是阅读；更多功能折叠，点开可选。

【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/38857841-d665e320-425c-11e8-8eb6-1ebec43f02e2.png)

![image](https://user-images.githubusercontent.com/31027645/38858010-41ca5da8-425d-11e8-91dd-29c21255f37d.png)

**Comment by Xiqiao** [comment]
已解决，感谢您提交的修改意见
