### ISSUE TITLE
创建内容的标题栏没有限制输入长度或已有限制不合理

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#29]
【bug标题】创建内容的标题栏没有限制输入长度或已有限制不合理
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.创建一条内容时，在标题栏输入超长字符，提交保存时提示：error: [object Object]
2.标题栏没有限制输入长度或已有限制不合理
3.实际输入约220多字符长度，可提交——但这个长度依然挺长的
【bug截图】
【备注】
![image](https://user-images.githubusercontent.com/31027645/38859804-648709d2-4261-11e8-8933-1ddc6df8717c.png)

![image](https://user-images.githubusercontent.com/31027645/38859399-828b608c-4260-11e8-8e79-f72adf25c9c5.png)

**Comment by raimonfuns** [comment]
已修复
