### ISSUE TITLE
blog的home页并没有展示最新文章，仍为旧文

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#3]
【bug标题】blog的home页并没有展示最新文章，仍为旧文
【测试版本】http://blog.press.one/，2018/4/16
【测试环境】不限
【复现频次】总是
【复现步骤】
1.检查archives最新文章，为《PRESS.one 项目更新 20180416》
2.检查home页，或直接访问http://blog.press.one/，为《PRESS.one团队回答社群疑问（2）》
3.即：home页并没有展示最新文章，对于很多直接用http://blog.press.one/访问博客的人来说，这是个问题。
【bug截图】

![image](https://user-images.githubusercontent.com/31027645/38812209-413e7a44-41be-11e8-8b19-66fb188a1a56.png)
![image](https://user-images.githubusercontent.com/31027645/38812229-4fdc9158-41be-11e8-968d-462ba502bc80.png)

【备注】无

**Comment by virushuo** [comment]
缓存没刷新，已经解决了并且更新到最新样式。
