### ISSUE TITLE
绑定微博反复多次不成功

### ISSUE THREAD

**Issue by richerwill** [Press-One/issues#30]
绑定微博时，在添加身份认证弹出窗口页面，我完成了三个步骤后，第四行显示“身份认证添加成功”，然后我点“完成”。
但是回到个人主页时，发现微博按钮还是灰色状态。我又反复试了几次，依然如此。

备注：
1）由于绑定微博时，我第一次操作的时候，在需要把微博上发送了数字签名的链接贴回到pressone时，不小心在页面旁边点了一下，然后添加身份认证的窗口就消失了，于是我又从头操作了一遍，也就是在微博上重新发了第二条数字签名，并把第二条微博的链接贴回pressone。最终显示我认证成功，但微博按钮依然是灰色状态。
2）微博的链接，由于在电脑端招不到复制链接的地方，我就从手机端打开微博，然后复制的链接。
3）我用的电脑是 Thinkpad x1   浏览器是chrome 。

**Comment by virushuo** [comment]
请提供一下 press.one 的个人页面url便于查找问题？
