### ISSUE TITLE
密码输入框总是会自动填充密码，错误提示不友好

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#31]
【bug标题】密码输入框总是会自动填充密码
【测试版本】all
【测试环境】pc，chrome
【复现频次】always
【复现步骤】
1.登录需要输入密码时，新建内容签名提交保存需要输入密码时，为什么密码输入框已经自动填充了密码？
2.自动填充的密码又总是错误的，但返回提示难以理解，并不直白
3.
【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/38868859-3b2325d4-427b-11e8-9139-87a16557e021.png)

**Comment by virushuo** [comment]
这个是浏览器的问题，应该禁止浏览器自动填充密码。

**Comment by raimonfuns** [comment]
已修复
