### ISSUE TITLE
新建内容签名提交保存的小页面有滑动条很丑

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#32]
【bug标题】新建内容签名提交保存的小页面有滑动条很丑
【测试版本】all
【测试环境】pc，chrome
【复现频次】always
【复现步骤】
1.新建内容签名，提交保存的页面非常小，但居然需要滑动条，很丑。见截图，盼优化
2.
3.
【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/38868859-3b2325d4-427b-11e8-9139-87a16557e021.png)

**Comment by raimonfuns** [comment]
已修复

**Comment by liujuanjuan1984** [comment]
确实已经修复了。~
