### ISSUE TITLE
签名创建页面在没有编辑的情况下有错误提示

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#33]
【bug标题】签名创建页面在没有编辑的情况下有错误提示

【测试版本】
http://dev.press.one/editor

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 登录后进入签名创建页面

【bug截图】
![sign-show-error](https://user-images.githubusercontent.com/7984510/38870484-8c8e1f82-4280-11e8-9c8e-f6f85ec7ef7d.gif)

【备注】
刚进入页面，就显示报错信息我觉得不合适

**Comment by virushuo** [comment]
这个不是报错，算警告提示。
