### ISSUE TITLE
签名创建页面没有给markdown的学习地址

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#34]
【bug标题】签名创建页面没有给markdown的学习地址

【测试版本】
http://dev.press.one/editor

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 登录后进入签名创建页面

【bug截图】
![use-markdown-write](https://user-images.githubusercontent.com/7984510/38871266-e9f7eeda-4282-11e8-9a1c-5b2e7ab546ba.gif)

【备注】
对没有用过这种编辑形式的人不友好。
应该给个地址来学习，或者给个名字让人去搜用法

**Comment by Xiqiao** [comment]
开发中
