### ISSUE TITLE
签名展示页面左侧的编辑按钮误导可以编辑现有文章

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#35]
【bug标题】签名展示页面左侧的编辑按钮应该是添加

【测试版本】
单个签名内容展示页面

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 点击签名的内容列表进入签名展示页面
2 左侧显示一个编辑按钮，我以为可以对这篇文章编辑
点击后发现是新建一个。

【bug截图】
![update-button-change-add](https://user-images.githubusercontent.com/7984510/38872060-f2fa3630-4284-11e8-9f74-3a1ed4b171d4.gif)

【备注】
改为添加按钮更合适一些

**Comment by Xiqiao** [comment]
已解决，感谢您提交的修改意见
