### ISSUE TITLE
签名编辑页面虽然提示标题必须写，但是不写也能提交

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#36]
【bug标题】签名编辑页面虽然提示标题必须写，但是不写也能提交

【测试版本】
签名编辑页面

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 进入签名编辑页面
2 不写标题直接提交
3 写入文章内容
4 提交成功

【bug截图】
![editor-no-title-but-right](https://user-images.githubusercontent.com/7984510/38873515-813d8da4-4288-11e8-8f8e-3ba045645330.gif)

【备注】

**Comment by raimonfuns** [comment]
已修复
