### ISSUE TITLE
签名编辑页面内容写空格可以提交

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#38]
【bug标题】签名编辑页面内容写空格可以提交

【测试版本】
签名编辑页面

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 进入签名编辑页面
2 不写标题，内容写空格直接提交
3 提交成功

【bug截图】
![editor-no-content-but-right](https://user-images.githubusercontent.com/7984510/38873795-31ecd39e-4289-11e8-8028-5cd10b3e1739.gif)

【备注】

**Comment by raimonfuns** [comment]
已修复
