### ISSUE TITLE
【个人信息】当Big.one 账号ID留空进行保存后，个人信息中仍显示了“*******************”

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#39]
【bug标题】当Big.one 账号ID留空进行保存后，个人信息中仍显示了“*******************”
【测试版本】all
【测试环境】PC，猎豹浏览器（chrome内核）
【复现频次】always
【复现步骤】
1.新注册用户，在个人信息中填写Big.one 账号ID，进行保存
2.编辑个人信息，将Big.one 账号ID的信息全部清除，进行保存
3.查看保存后的个人信息
【bug截图】
![2345 20180417213021](https://user-images.githubusercontent.com/38434418/38874036-b9a3496c-4289-11e8-972d-d80835fe6ef6.jpg)
![2345 20180417213033](https://user-images.githubusercontent.com/38434418/38874040-bc4aff2a-4289-11e8-9c20-42f26db92c62.jpg)

**Comment by raimonfuns** [comment]
已修复
