### ISSUE TITLE
团队blog页没有快速链接返回官网首页

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#4]
【bug标题】团队blog页没有快速链接返回官网首页
【测试版本】all
【测试环境】all
【复现频次】总是
【复现步骤】
1.在团队博客页http://blog.press.one/ ，无法找到快速跳转到http://blog.press.one/ 的入口
2.
3.
【bug截图】
【备注】

**Comment by raimonfuns** [comment]
已修复
