### ISSUE TITLE
在dev.press.one查看官网博客，跳转的地址是press.one

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#41]
【bug标题】在dev.press.one查看官网博客，跳转的地址是press.one

【测试版本】 https://dev.press.one/

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 进入https://dev.press.one/
2 点击右下角进入官方Blog
3 点击左上角pressOne的logo，跳转至了https://press.one/

【bug截图】
![jump-eror-to-dev](https://user-images.githubusercontent.com/7984510/38935034-d8a93bde-434f-11e8-9672-4c77f61f93b8.gif)

【备注】
这个其实不算bug，但是对于测试人员来说，如果没注意的话，很可能会把正式服务器当做测试服务器。
导致一些不良影响。建议将博客copy一份，改一下跳转地址

**Comment by raimonfuns** [comment]
已优化
