### ISSUE TITLE
没有登录依然可以设置用户名信息

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#42]
【bug标题】没有登录依然可以设置用户名信息

【测试版本】 http://dev.press.one/wizard

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 退出登录后，手动访问地址
http://dev.press.one/wizard

【bug截图】
![no-login-but-can-set](https://user-images.githubusercontent.com/7984510/38939650-ff1bc4d4-435a-11e8-8c2a-ab80709afec5.gif)

【备注】

**Comment by raimonfuns** [comment]
@nanjixiong 我这边是正常的，在没有登录的情况下，访问wizard页面，会被重定向到login页面。

![wizard](https://user-images.githubusercontent.com/8716838/38973206-117230ba-43d7-11e8-9107-ad7621886c8d.gif)

你关掉浏览器再重新试试？

**Comment by raimonfuns** [comment]
我先把 issue 关掉，如果还有这个问题再重新开个 issues。
