### ISSUE TITLE
已经登录了依然可以访问注册和初始设置界面

### ISSUE THREAD

**Issue by nanjixiong** [Press-One/issues#43]
【bug标题】已经登录了依然可以访问注册和初始设置界面

【测试版本】 
http://dev.press.one/wizard
http://dev.press.one/sign-up

【测试环境】所有

【复现频次】总是复现

【复现步骤】
1 登录后，手动访问地址
http://dev.press.one/wizard
http://dev.press.one/sign-up

【bug截图】
![login-but-can-regist](https://user-images.githubusercontent.com/7984510/38939976-b6665bea-435b-11e8-8696-9e74bae5992a.gif)

【备注】
已经登录的用户不应该能看到
http://dev.press.one/wizard
http://dev.press.one/sign-up
这两个界面。
且http://dev.press.one/wizard界面中名字写空格也被允许通过

**Comment by raimonfuns** [comment]
已经登录的用户是可以访问 wizard 页面的，比如新用户注册的时候，就会引导到 wizard 页面，完善个人信息。

已登录用户现在无法访问login和signup页面了，已修复。
