### ISSUE TITLE
【bug】按照注册流程注册，头像不会被保存

### ISSUE THREAD

**Issue by 276246413** [Press-One/issues#45]
【测试版本】全部
【测试环境】全部
【复现频段】随时
【复现步骤】
1.登录网页注册press
2.根据流程走，第二步，更换头像，随意选择一张照片上传，点击下一步，完成创建
3 头像不会被保存。
【bug截图】
【备注】
![qq 20180426130928](https://user-images.githubusercontent.com/38745736/39287027-fe35b22e-4953-11e8-9384-176df1cd7b2d.png)
![qq 20180426130944](https://user-images.githubusercontent.com/38745736/39287029-004cc02a-4954-11e8-89e2-9a0671de8029.png)

**Comment by chaoslaw2018** [comment]
需要先点击“保存头像”，再点击“下一步”才会保存。感觉是个用户体验问题。

**Comment by raimonfuns** [comment]
已优化
