### ISSUE TITLE
机构帐号身份认证页面的头像是普通用户，且无认证标识

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#46]
【bug标题】机构帐号身份认证页面的头像是圆形，不是方形
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.查看机构帐号的身份认证页https://press.one/p/address/v?s=d79a58b4d0f1c88344fbd24469d196d2db65b56fa9ab0d9fce20c466fc8084da84e225318b2376d8a5e2be839a8f929310c3296cc88b124a6ece3331db13ee480&h=bd90bbc0d07dbf0a3d153014958ae89a85857d746848ff87cfb2f5b20fc643f9&a=e0b2908b00ecc554e460863ee43481b8d47e8641&f=P1&v=2
2.发现身份认证页的头像是圆形（普通用户），不是方形（机构用户），截图1处标记
3.建议在该页面机构名字旁增加认证标识，比如截图2处标记
【bug截图】
![image](https://user-images.githubusercontent.com/31027645/39303927-813a5cac-498a-11e8-9989-0283b5d93dc2.png)

【备注】

**Comment by Xiqiao** [comment]
状态：产品优化
解决方式：下个版本更新
