### ISSUE TITLE
基金帐号的一句话描述与目标参与方限制字数偏少，建议放宽要求

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#47]
【bug标题】基金帐号的一句话描述与目标参与方限制字数偏少，建议放宽要求
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.如图，基金帐号的一句话描述限制30字，目标参与方限制20字，明显不够用。比如PRESS.one都不得不简写为PRS。且每个字母或标点符号算1个字，1个汉字也算1个字…
2.
3.
【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/39303996-bcbb754a-498a-11e8-8db2-7c20ab82ed47.png)

**Comment by Xiqiao** [comment]
状态：已列入产品优化规划
解决方式：下个版本更新
