### ISSUE TITLE
身份认证无法绑定小密圈/知识星球

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#48]
【bug标题】身份认证无法绑定小密圈/知识星球
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.身份认证时，选择个人网站类型
2.把身份签名信息发布到知识星球（拓荒者知识星球），选择单条信息的复制链接，结果认证失败，提示：抱歉，你返回的页面中没有包含数字签名，或数字签名链接显示不完整/不正确，请修正后重试。
3.注：主要是无法获取那条签名信息的网址，或者点击时间打开生成的页面，也不是那条信息的单独页面
【bug截图】
![image](https://user-images.githubusercontent.com/31027645/39304330-ea31b04c-498b-11e8-9924-df6c9b2600db.png)

【备注】

**Comment by raimonfuns** [comment]
小密圈暂时不支持认证。
