### ISSUE TITLE
已登录时，通过身份签名打开新页面是未登录状态

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#49]
【bug标题】已登录时，通过身份签名打开新页面是未登录状态
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.已登录pressone页面
2.这时通过网页版知识星球pressone的签名信息打开https://press.one/p/address/v?s=d79a58b4d0f1c88344fbd24469d196d2db65b56fa9ab0d9fce20c466fc8084da84e225318b2376d8a5e2be839a8f929310c3296cc88b124a6ece3331db13ee480&h=bd90bbc0d07dbf0a3d153014958ae89a85857d746848ff87cfb2f5b20fc643f9&a=e0b2908b00ecc554e460863ee43481b8d47e8641&f=P1&v=2
3.发现该页面中，我未登录；刷新页面，或者点击该页面回到首页，都是未登录状态
4.在另外一个已登录页面中，也能正常继续操作
【bug截图】
【备注】

**Comment by raimonfuns** [comment]
和这个问题相同。后续会对登录，注册进行大改版，这个问题就得到解决。 #126
