### ISSUE TITLE
中文网站登入时的出错提示为英文

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#5]
【bug标题】中文网站登入时的出错提示为英文
【测试版本】
【测试环境】all
【复现频次】always
【复现步骤】
1.在网页 https://press.one/sign-up 输入不合规范时，所有的提示文本为英文，对中文用户不友好
2.出错提示应与网站的语言版本保持一致，如果是中文站，都应为中文提示
3.
【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/38813740-5fc29906-41c2-11e8-8db9-617c73ce62fe.png)

**Comment by raimonfuns** [comment]
已修复
