### ISSUE TITLE
机构帐号，编辑介绍或公告时，支持n个换行符

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#50]
【bug标题】机构帐号，编辑介绍或公告时，支持n个换行符
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.机构帐号，编辑介绍，或公告时，支持n个换行符，如截图所示
2.是否最好限制下多个换行符自动执行1个换行？——不过用户可能也并不会这样故意把自己的页面搞的很丑吧。
3.
【bug截图】
![image](https://user-images.githubusercontent.com/31027645/39304905-e8df8e88-498d-11e8-90dc-cd37f7af7720.png)

【备注】

**Comment by raimonfuns** [comment]
已优化

**Comment by liujuanjuan1984** [comment]
尝试了下，该问题依然存在，并未实现。

请reopen @raimonfuns
