### ISSUE TITLE
机构帐号编辑时的标题文本字体太小

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#51]
【bug标题】机构帐号编辑时的提示文本字体太小
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.如截图所示，**机构名称**与**在这里填写公告**这类标题，字体都太小了
2.且和另外一类文本，如**不超过200个字**字体大小不一致，也会显得页面乱乱的
3.
【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/39305080-69ebfd0e-498e-11e8-8b43-386384a55bdb.png)

**Comment by Xiqiao** [comment]
建议修改为11px的字号

**Comment by raimonfuns** [comment]
已优化

**Comment by liujuanjuan1984** [comment]
![image](https://user-images.githubusercontent.com/31027645/40175639-5d38d3b0-5a0b-11e8-8c74-1278bcbccf4f.png)

不行。我申请reopen

现在的字体大小还是有2种，其中字体较小的那个，太难看清楚了。
