### ISSUE TITLE
发布大篇幅内容时，仅有页面生成滑动条，编辑器未生成滑动条

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#52]
【bug标题】发布大篇幅内容时，仅有页面生成滑动条，编辑器未生成滑动条
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.发布大篇幅内容时，仅有页面生成滑动条，编辑器未生成滑动条
2.导致，内容需要往下翻，只能翻动页面滑动条，于是导致无法使用编辑器工具栏
3.期望生成编辑器框的滑动条
【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/39306490-ebd87fa0-4992-11e8-90e0-73def94309b8.png)

**Comment by raimonfuns** [comment]
1. 编辑器是打算不加滚动条的。因为如果编辑器加滚动条，会和页面的滚动条形成双重滚动，体验不好。
2. 现在编辑器是没有滚动条的，内容100%展开，和微信公众号后台的编辑器是一样的，理论上不会遮住内容才对，如图。
3. 编辑器工具栏现在可以随着页面的滚动，一直显示在屏幕的上方。

**Comment by liujuanjuan1984** [comment]
当前实现方式满足使用需求了。
