### ISSUE TITLE
编辑器预览长篇幅内容时，超长内容没有显示出来

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#53]
【bug标题】编辑器预览长篇幅内容时，超长内容没有显示出来
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.见图所示，预览大篇幅内容，到了某个长度后续内容就无法展现出来
2.页面自身的滑动条无法实现内容的滚动展示更多
3.
【bug截图】
【备注】
![image](https://user-images.githubusercontent.com/31027645/39306871-eb3168b8-4993-11e8-8804-f774d65731a3.png)

**Comment by raimonfuns** [comment]
1. 编辑器是打算不加滚动条的。因为如果编辑器加滚动条，会和页面的滚动条形成双重滚动，体验不好。
2. 现在编辑器是没有滚动条的，内容100%展开，和微信公众号后台的编辑器是一样的，理论上不会遮住内容才对。
3. 编辑器工具栏现在可以随着页面的滚动，一直显示在屏幕的上方。

![test](https://user-images.githubusercontent.com/8716838/39752737-e84eae30-52ee-11e8-9c20-c5c846ab765d.gif)

**Comment by liujuanjuan1984** [comment]
OK，新功能体验了，正常了。

**Comment by liujuanjuan1984** [comment]
这个bug依然存在。

**Comment by raimonfuns** [comment]
已修复
