### ISSUE TITLE
登陆没有找回密码选项

### ISSUE THREAD

**Issue by OTTChaos** [Press-One/issues#54]
【bug标题】登陆时没有密码提示以及找回密码选项
【测试版本】all
【测试环境】all
【复现频次】总是复现
【复现步骤】登陆账户时，多次输入密码错误后，没有密码提示以及找回密码选项
【bug截图】
![image](https://user-images.githubusercontent.com/38761377/39319133-c41e128e-49b2-11e8-9bfe-31564586df1a.png)

【备注】无

**Comment by chaoslaw2018** [comment]
目前，去中心化的项目应该是没有找回密码的

**Comment by raimonfuns** [comment]
@OTTChaos  暂不提供找回密码功能
