### ISSUE TITLE
内容编辑页面应提示「支持Markdown编辑器」，缺乏新手指导提示

### ISSUE THREAD

**Issue by OTTChaos** [Press-One/issues#57]
【bug标题】内容编辑页面应提示「支持Markdown编辑器」，缺乏新手指导提示
【测试版本】all
【测试环境】all
【复现频次】总是复现
【复现步骤】打开内容编辑器后，并无提示「支持Markdown编辑器」，对于新手使用者，缺乏Markdown使用格式的新手指引或功能提示
【bug截图】
【备注】如有，可添加附注

**Comment by Xiqiao** [comment]
开发中
