### ISSUE TITLE
个人页面以及生成内容签名页面没有草稿箱（历史版本）功能

### ISSUE THREAD

**Issue by OTTChaos** [Press-One/issues#58]
【bug标题】个人页面以及生成内容签名页面没有草稿箱（历史版本）功能
【测试版本】all
【测试环境】Mac wifi
【复现频次】总是复现
【复现步骤】个人页面以及生成内容签名页面没有草稿箱功能
【备注】生成内容签名页面建议增加自动保存功能

**Comment by Xiqiao** [comment]
草稿箱开发中
