### ISSUE TITLE
自己保存keystore注册新账号，并未强制用户自己备份文件

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#6]
【bug标题】自己保存keystore注册新账号，并未强制用户自己备份文件
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.注册新帐号，选择自己保存keystore的方式
2.帐号已经生成，此时界面有**备份**和**前往主页**两个功能
3.如果不点击备份，直接点击**前往**主页，会导致用户无法再次登入，相当于白白注册了
4.建议如果备份keystore是必须的，请在注册后设置一个独立环节，让用户**备份**；备份之后再提供前往主页的功能，即不要在同一个操作环节给2个操作选项，
【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/38822262-7adb245c-41d5-11e8-88a5-387499ee39bd.png)

**Comment by raimonfuns** [comment]
后续登录，注册会大改版。也就不会有这个问题了。
