### ISSUE TITLE
【bug】中文邮箱也可以注册

### ISSUE THREAD

**Issue by 276246413** [Press-One/issues#61]
【测试版本】全部
【测试环境】全部
【复现频段】随时
【复现步骤】
1、注册邮箱使用中文名字注册，显示可以注册成功
【bug截图】
![11](https://user-images.githubusercontent.com/38745736/39390928-754911a0-4ace-11e8-97df-969b1d40d540.png)

【备注

**Comment by chaoslaw2018** [comment]
官方认定不做校验，参见：
https://github.com/Press-One/issues/issues/71
