### ISSUE TITLE
【建议 or  bug】签名内容，最原始在最上

### ISSUE THREAD

**Issue by 276246413** [Press-One/issues#66]
【测试版本】全部
【测试环境】全部
【复现频段】随时
【复现步骤】
1、人的视觉都是从上到下，从左到右，应该吧最新的放在最上面，符合人的视觉本能
【bug截图】
![55](https://user-images.githubusercontent.com/38745736/39391208-97af5c28-4ad2-11e8-884b-5a43925c1d55.png)

【备注】

**Comment by Xiqiao** [comment]
状态：会在下个 post list 的 功能迭代版本中处理。
解决方案：按照从新到旧排序。等给 post list 加分类功能时一起处理。

**Comment by Xiqiao** [comment]
已解决，感谢您提交的修改意见
