### ISSUE TITLE
【兼容性】苹果手机自带输入法，无法输入汉字

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#67]
【bug标题】苹果手机自带输入法，无法输入汉字
【测试版本】all
【测试环境】IOS，移动端
【复现频次】always
【复现步骤】
1.用户在iPhone上用Safari登录后，跳转到生成内容签名页面
2.在Content输入框中用iPhone自带输入法输入汉字
3.输入的汉字变为乱码，无法输入汉字
【备注】
1.经霍炬确认，可能是Safari和iPhone输入法有什么奇怪的冲突。
2.本问题由志愿者@洛克飞鸟 提出，本人代提交。
![20180430131527](https://user-images.githubusercontent.com/38434418/39415666-b8b89306-4c78-11e8-97a8-e32affbbdbc8.jpg)

**Comment by Xiqiao** [comment]
状态：已转给前端团队
解决方案：所选用MD编辑器开源方案的bug, 很难解决。需要更换MD编辑器。

**Comment by raimonfuns** [comment]
已修复
