### ISSUE TITLE
【登录】Pressone无法登录，并报错

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#68]
【bug标题】Pressone无法登录，并报错
【测试版本】all
【测试环境】PC
【复现频次】always
【复现步骤】
1.在Pressone进行登录
2.无法登录，并报错“GETKEYSTOREFROMSERVER ERROR: UNKNOWN”
【备注】
1.经霍炬确认，可能是登录时系统正在更新造成的。
2.本问题由志愿者@lmy 提出，本人代提交。
![20180430131833](https://user-images.githubusercontent.com/38434418/39415729-7a6a3a36-4c79-11e8-8a33-a0f2cdca9856.jpg)

**Comment by Xiqiao** [comment]
状态：关闭
关闭原因：经霍炬确认，可能是登录时系统正在更新造成的。
