### ISSUE TITLE
【注册】自己保存keystore文件注册时，对重复的email地址未做校验

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#69]
【bug标题】自己保存keystore文件注册时，对重复的email地址未做校验
【测试版本】all
【测试环境】PC
【复现频次】always
【复现步骤】
1.新注册用户，使用“11@11.com”进行注册（勾选“我选择自己保存我的keystore文件”）
2.退出登录，再次使用“11@11.com”进行注册（勾选“我选择自己保存我的keystore文件”）
3.两个账号都能注册成功，并登录使用
【备注】
1.本问题由志愿者@辽阳联通-显贸 提出，本人代提交。

**Comment by Xiqiao** [comment]
状态：转给后端团队。
解决方案：现在注册邮箱地址有作重复校验吗？

**Comment by raimonfuns** [comment]
已加上重复邮箱校验。
