### ISSUE TITLE
选择身份认证类型时，选中效果不突出难以辨识

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#7]
【bug标题】选择身份认证类型时，选中效果不突出难以辨识
【测试版本】all
【测试环境】all
【复现频次】allways
【复现步骤】
1.打开选择身份认证类型
2.首次打开，默认选中个人网站，但其实我完全没有意识到它已经选中了个人网站，当时完全不知道如何操作
3.目前仅是用白色与灰色来区分选中和未选中，建议选中增加一个绿色√，更易被理解
【bug截图】
【备注】
![image](https://user-images.githubusercontent.com/31027645/38822782-0b985590-41d7-11e8-81ae-3051fe075016.png)

**Comment by Xiqiao** [comment]
状态：已加入改进计划。解决方案：白色改为蓝色。

**Comment by raimonfuns** [comment]
已优化
