### ISSUE TITLE
[建议or Bug]PRESSone 注册时不会对注册的邮箱进行有效验证

### ISSUE THREAD

**Issue by yulinliujian** [Press-One/issues#71]
注册PRESSone 时，邮箱可以随意输入，只要满足xxxxx@xxx.com 就可以通过。
比如我注册时，随便输入一个地址都能注册成功

![image](https://user-images.githubusercontent.com/29038837/39612829-43272a74-4f95-11e8-994b-ac17bb304feb.png)

![image](https://user-images.githubusercontent.com/29038837/39612859-6ec26162-4f95-11e8-9638-6efc787e208d.png)

**Comment by virushuo** [comment]
这个确实是不验证的，因为用户不做为任何凭证，只是登录的用户名而已。我们目前不会使用用户邮箱直接做什么事情，也就没必要验证它。
