### ISSUE TITLE
手机端点击基金帐号认证icon，没有tips显示

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#72]
【bug标题】手机端点击基金帐号认证icon，没有tips显示
【测试版本】all
【测试环境】苹果手机，safari
【复现频次】always
【复现步骤】
1.手机端访问基金帐号页面 https://press.one/main/p/e0b2908b00ecc554e460863ee43481b8d47e8641 
2. 尝试点击基金帐号头像旁边的认证图标
3.没有tips展示
【bug截图】

【备注】

**Comment by raimonfuns** [comment]
@liujuanjuan1984 在手机端，tips的显示是需要长按触发的。

**Comment by liujuanjuan1984** [comment]
OK，试了下，确实长按就触发了tips
