### ISSUE TITLE
【兼容性】手机端，关闭退出弹层会让页面无法进行其他操作

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#74]
【bug标题】手机端，关闭退出弹层会让页面无法进行其他操作
【测试版本】all
【测试环境】IOS Safari浏览器，ANDROID 小米浏览器
【复现频次】always
【复现步骤】
1.用户使用手机浏览器进行登录
2.在“我的页面”点击右上角的”三点“菜单
3.点击菜单外的任何区域
4.整个页面的点击区域全部失效，点击任何按钮都无法跳转
【备注】
1.本问题由志愿者@王晓龙提出，本人代提交。
2.猜测是菜单虽然在页面上不显示，但蒙版事件或菜单层并未清除。
【截图】
![20180506203540](https://user-images.githubusercontent.com/38434418/39673415-4e597318-516e-11e8-9a1b-cbb355d0358d.jpg)
![20180506204834](https://user-images.githubusercontent.com/38434418/39673447-fb40036c-516e-11e8-800f-9ac4c383fcfd.jpg)

**Comment by raimonfuns** [comment]
已修复
