### ISSUE TITLE
Press-One页面保存不读取文章标题，永远都是PRESS.one

### ISSUE THREAD

**Issue by somexin** [Press-One/issues#75]
将Press-One页面保存书签的时候，书签标题永远都是PRESS.one，为以后寻找文章造成很大困扰。类比简书会抓取文章标题：如“大型分布式网站架构：缓存在分布式系统中的应用 - 简书”，有标题名，也有网站名字。
![image](https://user-images.githubusercontent.com/24487052/39741932-48474e8a-52ce-11e8-9b1e-2ea637fb93cc.png)
![image](https://user-images.githubusercontent.com/24487052/39741943-503a740a-52ce-11e8-9b71-cbbe86932501.png)
![image](https://user-images.githubusercontent.com/24487052/39741947-5684356c-52ce-11e8-9906-4f95db90abb7.png)

**Comment by raimonfuns** [comment]
已优化
