### ISSUE TITLE
【兼容性】手机端，blog页面分割符号与下方文字重叠

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#77]
【bug标题】手机端，blog页面分隔符号与下方文字重叠
【测试版本】all
【测试环境】小米note 2，miui自带浏览器
【复现频次】always
【复现步骤】
1.使用手机浏览器，浏览https://blog.press.one/
2.从”PRESS.one 项目更新 20180416“这篇开始，之前的文章标题与上方的分隔符有重叠
【截图】
![20180509225115](https://user-images.githubusercontent.com/38434418/39821762-83403200-53db-11e8-89af-84d9f8985bff.jpg)
![20180509225134](https://user-images.githubusercontent.com/38434418/39821796-93aca34e-53db-11e8-8f74-71025a8da3b6.jpg)

**Comment by raimonfuns** [comment]
@chaoslaw2018 
以后项目的进展会在公众号（PRESSone数字内容交易分发网络）中更新，所以这个问题不做优化。多谢反馈。

奖励：2 PRS
