### ISSUE TITLE
绑定twitter身份认证shi时，自动识别了旧帐号的绑定信息

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#79]
【bug标题】绑定twitter身份认证shi时，自动识别了旧帐号的绑定信息
【测试版本】all
【测试环境】PC，window系统，chrome浏览器
【复现频次】always
【复现步骤】
1.很久之前，我的个人twitter帐号，绑定过个人PRS页面；我的电脑浏览器中，个人twitter保持登录状态，即访问twitter则自动已登录；
2.今晚尝试绑定基金帐号的twitter；已登入基金的PRS页面；
3.先退出个人twitter，注册基金帐号的twitter
4.点击PRS页面的身份认证，选择了twitter，没有任何弹窗或下一步或任何确认环节，就直接通过了步骤2，绑定完成
5.访问PRS页面上的该twitter帐号，结果跳转到个人twitter身份签名页面那条推
6.尝试重新绑定一次twitter，才有了确认授权环节
【bug截图】

【备注】

**Comment by Leask** [comment]
已经修复。
