### ISSUE TITLE
头像设置页面的功能按钮未能显示在一屏视野内

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#8]
【bug标题】头像设置页面的功能按钮未能显示在一屏视野内
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.注册后设置头像环节，该网页太大了，滑动条很丑，且操作按钮完全被挡住了，不下翻根本注意不到
2.用手机注册时也遇到这个问题，即，操作按钮超出了当前一屏的范围，完全没看到
3.
【bug截图】
【备注】
![image](https://user-images.githubusercontent.com/31027645/38822977-b2e63f38-41d7-11e8-9ed7-7e7621009269.png)

**Comment by raimonfuns** [comment]
已修复
