### ISSUE TITLE
通过社交网站身份认证链接访问到的页面，机构帐号标识不足

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#80]
【bug标题】通过社交网站身份认证链接访问到的页面，机构帐号标识不足
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.在基金twitter帐号 https://twitter.com/PRESSone_fans 访问身份认证链接 https://t.co/YiG3aP26fn
2.跳转到了页面 https://press.one/p/address/v?s=d79a58b4d0f1c88344fbd24469d196d2db65b56fa9ab0d9fce20c466fc8084da84e225318b2376d8a5e2be839a8f929310c3296cc88b124a6ece3331db13ee480&h=bd90bbc0d07dbf0a3d153014958ae89a85857d746848ff87cfb2f5b20fc643f9&a=e0b2908b00ecc554e460863ee43481b8d47e8641&f=P1&v=2 
3.该页面，有几处小问题：见截图标记
 >您当前访问到的是一条在Press.one被数字签名过的身份验证信息  多了一个符号>
基金帐号头像是圆形的，而不是机构类帐号应有的方形
基金帐号旁边没有身份认证图标
![image](https://user-images.githubusercontent.com/31027645/40133741-2f2027a0-5973-11e8-88f3-fc6411508b49.png)

而通过基金帐号的内容签名展现的内容则相对更正式一点。
![image](https://user-images.githubusercontent.com/31027645/40133763-41335f8e-5973-11e8-8300-2184835cf6f7.png)

【bug截图】
【备注】

**Comment by raimonfuns** [comment]
已修复。

奖励：3 PRS
