### ISSUE TITLE
无法绑定币乎

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#81]
【bug标题】无法绑定币乎
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.尝试绑定币乎，选择个人网站类型，输入签名文章地址https://bihu.com/article/403813
2.无法绑定，提示：抱歉，你所提供的页面链接不能访问，请检查一下后重试。
3.
【bug截图】
【备注】

**Comment by raimonfuns** [comment]
@liujuanjuan1984 暂时还不支持币乎的绑定。
