### ISSUE TITLE
【绑定】当原账号忘记密码后，已绑定的iVeryOne无法更换绑定或解绑

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#82]
【bug标题】当原账号忘记密码后，已绑定的iVeryOne无法更换绑定或解绑
【测试版本】all
【测试环境】PC
【复现频次】always
【复现步骤】
1.pressone账号A关联过iVeryOne账号A，并忘记密码。
2.注册pressone账号B（与账号A用的同一个邮箱名），去关联iVeryOne账号A。
3.无法完成关联，并提示之前已有过账号绑定。
【备注】
1.本问题由志愿者@见路不走 提出，本人代提交。
2.@见路不走希望能有找回密码，或能够解绑、重绑的方式。

**Comment by raimonfuns** [comment]
这个是 iveryone 的限制，等后续他们支持此功能，这个问题就能得到解决。
