### ISSUE TITLE
 输入内容编辑时 输入法有错误

### ISSUE THREAD

**Issue by GraceXXu** [Press-One/issues#84]
【bug标题】输入内容编辑时，输入法有错误
【测试版本】all
【测试环境】iPhone 8S
【复现频次】总是复现
【复现步骤】在press.one上 生成新的内容签名，内容输入时，输入法有错误，跟输入字符不一致，必须全部删除后，再重新输入，中间不能有修改拼写一次全写对才能准确录入。 
【bug截图】
![1843014d-3f2c-4c64-b581-b57d69c5583a](https://user-images.githubusercontent.com/38451911/40275471-76519f72-5ba4-11e8-81fe-6421e9a249c7.png)

**Comment by raimonfuns** [comment]
@GraceXXu  编辑器的功能后续会优化。 #97
