### ISSUE TITLE
【个人页面】输入内容和下方横线不贴合

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#85]
【bug标题】输入内容和下方横线不贴合
【测试版本】dev
【测试环境】PC，猎豹浏览器
【复现频次】always
【复现步骤】
1.登录基金会类账号（截图中用的是org_test_01）。
2.编辑基本信息中的介绍。
3.编辑公告内容。
4.发现输入光标都在横线上方两行长度的位置。
【截图】
![1](https://user-images.githubusercontent.com/38434418/40275478-6295e05a-5c22-11e8-806e-7871382339c0.gif)
![3](https://user-images.githubusercontent.com/38434418/40275479-66ffb67a-5c22-11e8-82e9-3e4675d4fcd5.gif)

**Comment by Xiqiao** [comment]
这个是text area框，允许输入多行文字，你想象一下那是一个输入区域是一个有下边距的矩形框就好了。如果输入超过3行，这个输入区域的高度还可以拖拽增加。这个样式是google material design的标准表单样式。
