### ISSUE TITLE
【创建签名】创建签名时，Insert Image的初始光标位置改善

### ISSUE THREAD

**Issue by chaoslaw2018** [Press-One/issues#87]
【bug标题】创建签名时，Insert Image的初始光标位置改善
【测试版本】all
【测试环境】PC，猎豹浏览器
【复现频次】always
【复现步骤】
1.登录并在个人页面中点击创建签名。
2.在内容输入控件中点击Create Link，可以看到生成的字符中输入光标是在[]中间。
3.在内容输入控件中点击Insert Image，可以看到生成的字符中输入光标是在http://前面。
4.从用户角度来说，不合适的输入光标位置意味着要再多点一次，让光标移动到合适的位置。
5.建议将Insert Image的初始光标位置放到[]中间或http://后面。
【截图】
![2](https://user-images.githubusercontent.com/38434418/40275544-e2e84dcc-5c24-11e8-9947-9cae3884b4ab.gif)

**Comment by raimonfuns** [comment]
@chaoslaw2018 
插图图片时，[] 里面填的文本，作用是当图片无法正常显示，会显示改文本。
大部分情况下，都不需要填写改文本。只需要输入图片的链接即可。
是出于这个原因，才会把光标的位置放在括号中。
