### ISSUE TITLE
同时登录两个prs帐号后，绑定github时身份认证时报错

### ISSUE THREAD

**Issue by PRSpioneer** [Press-One/issues#88]
PC端，chrome浏览器
已登录pressone帐号A
然后另外开一个页面登录pressone帐号B
已登录github帐号C

尝试绑定帐号A与帐号C，身份认证弹出下述页面后，继续下一步时出错了
报错文本：saveProofToChain error: Invalid signature.

当刷新pressone页面时，发现显示的是帐号b处于登入状态
此时登出更换为帐号A，再次尝试帐号A与帐号C的身份认证，才成功完成。

![image](https://user-images.githubusercontent.com/39545854/40404452-8283296c-5e8a-11e8-98b1-43d3b1c6e25c.png)

![image](https://user-images.githubusercontent.com/39545854/40404423-5953fd96-5e8a-11e8-8a7c-4dfbe34f4f03.png)

**Comment by raimonfuns** [comment]
@PRSpioneer 这个问题，本质是和 #126 相同。等登录，注册优化改版之后就好了。
