### ISSUE TITLE
已经在Press-One上登录，但是点击一个press的链接后仍旧显示登录

### ISSUE THREAD

**Issue by huerbt** [Press-One/issues#89]
步骤如下：
1、在p1上登录我的帐号
2、在p1的拓荒者微信群里点击某个p1的链接比如：https://press.one/main/p/e0b2908b00ecc554e460863ee43481b8d47e8641
3、进入上述链接后页面的右上角显示“登录”“创建帐号”，而不是我的头像。

**Comment by raimonfuns** [comment]
和这个问题相同。 #126
