### ISSUE TITLE
keystore登录时，放入错误文件，没有任何有效提示

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#9]
【bug标题】keystore登录时，放入错误文件，没有任何有效提示
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.采用keystore登录，未选择任何文件时，提示：error: file is null
2.选择了一个无关文件放入，提示没有变化，依然是：error: file is null
3.刷新页面，重新采用keystore登录，选择一个无关文件，网页没有任何提示
4.应该提示用户选择keystore文件
【bug截图】
【备注】

![image](https://user-images.githubusercontent.com/31027645/38823257-7d019466-41d8-11e8-82d3-c232f44c2acb.png)

**Comment by raimonfuns** [comment]
已修复
