### ISSUE TITLE
查看其他用户信息时，头像仍是自己个人的头像信息

### ISSUE THREAD

**Issue by CharlesLiu7** [Press-One/issues#90]
如题：
![image](https://user-images.githubusercontent.com/8590736/40473849-ecd48870-5f6f-11e8-83df-44d1dd96c29d.png)
在我登录个人账号后，查看[PRS官方基金会 (PRS Official Foundation)](https://press.one/main/p/f21c398adcbd672a215bd12756c520c1372c408b)（注意是先登录个人账号，我的顺序是 登录->点击进入官方Blog->点击文章‘PRESS.one 项目更新 20180507’->点击基金会连接在新的浏览器tab里显示如上图），左侧仍然显示为我个人的账号信息，而不是PRS官方基金会账号信息。
![image](https://user-images.githubusercontent.com/8590736/40473921-314e6674-5f70-11e8-9199-e3a16e4ca133.png)
在我点击进入文章后，情况同样是如此。
点击左侧两篇文章那里后，显示的不是我个人的文章，而是第一个图片所展示的界面

【Press.One个人账号】https://press.one/main/p/effdab8e2b6437cb55923a480c5d2dc29a221f12
【Mixin ID】37027391

**Comment by CharlesLiu7** [comment]
【bug标题】查看其他用户信息时，头像仍是自己个人的头像信息
【测试版本】all
【测试环境】MacBook Air, Chrome
【复现频次】always

**Comment by raimonfuns** [comment]
已修复
