### ISSUE TITLE
BUG(添加身份认证)

### ISSUE THREAD

**Issue by cubyhuang** [Press-One/issues#92]
完成添加完微博或文章的页面网址后。
确认 3 把该条“包含您数字签名信息的页面网址”保存到区块链上

出现  （抱歉，你返回的页面中没有包含数字签名，或数字签名链接显示不完整，请修正后重试）

1.改了好几次都是这样的结果
2.如何正确的示范，可以放图
3.出现这种问题可以放个FAQ
4.总结所有的签名的正确操作方式来示范签名操作

**Comment by cubyhuang** [comment]
1.能否做个类似于勋章或者奖励任务一样的完成每一个签名文章。
2.每个任务都会有详细的操作示范让小白也可以跟着完成签名文章

**Comment by cubyhuang** [comment]
1.（选择添加身份类型）框上没有关闭按钮，需要点击外部图案才能关闭。
2.（选择添加身份类型）框不锁定，一点外面就关闭

**Comment by cubyhuang** [comment]
绑定big.one账号的提示是全英文的。有没有中文提示

**Comment by JiuOneOne** [comment]
1.新浪微博与steemit身份认证，完成添加完微博或文章的页面网址后，确认 3 把该条“包含您数字签名信息的页面网址”保存到区块链上，出现 “抱歉，你返回的页面中没有包含数字签名，或数字签名链接显示不完整，请修正后重试”，改了好几次都是这样的结果。之后再操作知乎却没有出现该问题。

2.签发的文字有没有可能修改错别字呢？就是那种划掉改正确的，就想老师批改学生作业加批注的方式，这样既保留了痕迹，又不至于眼睁睁看着错的，却改不了好太多。可不可以在微信订阅号文章改错字功能上优化一下这个。

**Comment by JiuOneOne** [comment]
yes，刚刚发这个上述文字错了个字，可重新编辑，就是一样的意思，既保留历史痕迹，又可以修改。

**Comment by raimonfuns** [comment]
@cubyhuang 
1. 绑定big.one账号的中文提示已加上。
2. 「抱歉，你返回的页面中没有包含数字签名，或数字签名链接显示不完整，请修正后重试」。微博由于有缓存，有可能会出现这种延时的问题。一般等几分钟再试就能成功的。

其他产品上的建议，已转发给 @Xiqiao
