### ISSUE TITLE
在已登录PRS帐号的页面中粘贴访问其他人的页面，信息无法刷新或刷新有误

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#93]
【bug标题】在已登录PRS帐号的页面中粘贴访问其他人的页面，信息无法刷新或刷新有误
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.在浏览器页面A中，已登录基金帐号X
2.新打开页面，粘贴其他人的页面，尝试直接访问，可以正常访问显示
3.在页面A中，粘贴其他人的页面，尝试直接访问，无法跳转，总是显示基金帐号X的首页（只有签名内容那里刷新了，身份信息和xiang'mu项目信息没刷新）
4.在页面A中，粘贴其他人的签名信息，点击【访问该内容】or【查看签名者的身份认证】总是跳转失败，跳转成功后，所显示的身份信息也不对，总是显示基金帐号X的身份信息（很容易误解成左侧的身份信息是右侧内容的创作者）

附：其他人的页面https://press.one/main/p/c7931127adec318f76a127fe83ed7fe38beef1e6
附2：其他人的签名信息https://press.one/file/v?s=f98fc2fe9a85bc2c2c6abd2724fa7db2dba47bf0fa50afc82ccd458e3880336cf4273a7a10829a1b7ef4dad43e832a3f602b899f1837dfd98f11b29fbfaf05481&h=d1a71992268d6b565c630032c4831a85a39559aa7215b245f0bdd8d1bb70f2f8&a=c7931127adec318f76a127fe83ed7fe38beef1e6&f=P1&v=2

![image](https://user-images.githubusercontent.com/31027645/40477815-f75d0218-5f79-11e8-88fc-5e568c4a0621.png)

![image](https://user-images.githubusercontent.com/31027645/40479633-b48f9162-5f7e-11e8-86e3-7ff15757cbcf.png)

【bug截图】
【备注】

**Comment by liujuanjuan1984** [comment]
该问题在移动端也同样存在。
登入prs拓荒者基金帐号后，打开hello ，pressone注册有礼的那篇内容
里面有很多其他人的链接页面，随便打开一篇，内容列表或内容详情是访问对象的，但身份信息全部显示的是基金帐号的。

**Comment by raimonfuns** [comment]
已修复
