### ISSUE TITLE
微信窗口转发文章预览页面总是变成身份签名页面

### ISSUE THREAD

**Issue by liujuanjuan1984** [Press-One/issues#95]
【bug标题】微信窗口转发文章预览页面总是变成身份签名页面
【测试版本】all
【测试环境】all
【复现频次】always
【复现步骤】
1.手机端，在微信窗口，访问任何一篇文章的预览页面
2.转发该预览页面到朋友圈，或微信聊天窗口
3.手机打开该页面，发现是身份签名页面，而不是文章预览页面
4.该问题的影响是，想要直接转发该内容，而不是转发该身份签名；直接展示身份签名，导致阅读内容还要再点击一次（如果很多人不懂点击哪里呢？）
【bug截图】

【备注】

**Comment by raimonfuns** [comment]
@liujuanjuan1984 这个问题我重现不了呢，我转发预览页面，打开也是预览页面。你现在还能重现吗？

**Comment by raimonfuns** [comment]
因为无法重现该问题，先关闭此 issue。
