### ISSUE TITLE
移动端编辑器体验问题

### ISSUE THREAD

**Issue by harryzhicheng** [Press-One/issues#97]
在移动端用浏览器打开页面，编辑一点内容后切换到其它app浏览，再次返回编辑，编辑内容主体显示不了键盘。并且移动端编辑内容主体，需要一气呵成，删除一点可能就会自动删除之前的部分内容，输入的拼音和显示的文字完全不符 #70 mixin id：1091861

**Comment by raimonfuns** [comment]
后续会换一个新的编辑器，让写文章的体验更好。

Mixin ID：1091861
奖励：3 PRS
