### ISSUE TITLE
签名过的内容无法在新的标签页打开

### ISSUE THREAD

**Issue by harryzhicheng** [Press-One/issues#98]
【bug标题】签名过的内容无法在新的标签页打开
【测试版本】全部
【测试环境】PC端
【复现频次】总是复现
【复现步骤】想在新的标签页打开签过名的内容，发现不可以，这样我浏览多个签过名的内容需要同时打开多个pressone页面
【bug截图】
![Uploading 微信图片_20180526220018.jpg…]()
#70mixin id：1091861

**Comment by raimonfuns** [comment]
已修复。

奖励：2 PRS.
