### ISSUE TITLE
登录状态显示错误

### ISSUE THREAD

**Issue by yy307** [Press-One/issues#99]
重现步骤:
1.打开press.one, 使用密钥方式登录
![wx20180529-002611](https://user-images.githubusercontent.com/314256/40622979-ee26f2ca-62d6-11e8-98ae-f2b63818b367.png)
2.打开pressone周报, 网址https://mp.weixin.qq.com/s/IQiy_b5MMJd1WP5ecFJCFg
3.从周报页面的网址(围观笑来的PRESSone页面：) 跳转pressone
https://press.one/main/p/d21044a0b2d54996be020e80864084b3a625b681
4.页面未显示自己当前的登录状态
![wx20180529-002452](https://user-images.githubusercontent.com/314256/40622966-d2de51d4-62d6-11e8-83b0-c880067a6ed9.png)

在Mac上的Chrome和Safari均可重现此问题

**Comment by qige-one** [comment]
同样经常感受到此问题

**Comment by raimonfuns** [comment]
#126
